import type { Lang } from './i18n';

export interface LandingT {
  tryFree: string; openApp: string;
  heroBadge: string; heroH1: [string, string]; heroSubtitle: string;
  heroPlaceholder: string; heroPlaceholderHint: string;
  removePhoto: string; photoAttached: string; uploadPhoto: string;
  stopRecording: string; speak: string; listening: string; send: string;
  invalidFile: string; analyzePhoto: string; noSignup: string;
  statsFree: string;
  demoLabel: string; demoSubtitle: string;
  tabDiagnosis: string; tabPlanning: string;
  confidence: string; organic: string; chemical: string; agronomicData: string;
  howLabel: string; howTitle: string;
  rolesLabel: string; rolesTitle: string; rolesInstruction: string;
  tryAs: (role: string) => string;
  featuresHeading: string; testimonialsLabel: string;
  pricingLabel: string; pricingTitle: string; pricingSubtitle: string;
  billingMonthly: string; billingAnnual: string;
  perMonth: string; perYear: string; noCreditCard: string; freeName: string; freeTagline: string;
  freeFeatures: string[]; getStartedFree: string;
  proYearlyNote: string; proTwoYearNote: string; proTagline: string; proFeatures: string[]; tryPro: string;
  agronomistName: string; agronomistBadge: string;
  agronomistYearlyNote: string; agronomistTwoYearNote: string; agronomistTagline: string;
  agronomistFeatures: string[]; startAgronomist: string;
  enterpriseBadge: string; enterpriseContact: string;
  enterpriseSubtitle: string; enterpriseFeatures: string[]; getInTouch: string;
  trialBadge: string;
  ctaHeadline: string; ctaBody: string; ctaButton: string; ctaFine: string;
  privacy: string; terms: string;
  docTitle: string; metaDesc: string; ogTitle: string; ogLocale: string;
  speechLang: string; askOli: string;
}

const el: LandingT = {
  tryFree: 'Δοκίμασε δωρεάν', openApp: 'Άνοιξε',
  heroBadge: 'Ο AI Γεωπόνος σου · 24/7',
  heroH1: ['Ο γεωπόνος σου.', 'Πάντα μαζί σου.'],
  heroSubtitle: 'Διάγνωση ασθενειών, σχεδιασμός φύτευσης, άρδευση, αναστήλωση χωραφιών. Από σπορά μέχρι συγκομιδή, ο Oli μαθαίνει τις καλλιέργειές σου.',
  heroPlaceholder: 'Ρώτα ή ανέβασε φωτογραφία...',
  heroPlaceholderHint: '(Shift+Enter για νέα γραμμή)',
  removePhoto: 'Αφαίρεση φωτογραφίας', photoAttached: 'Φωτογραφία επισυνάφθηκε',
  uploadPhoto: 'Ανέβασε φωτογραφία', stopRecording: 'Σταμάτα εγγραφή',
  speak: 'Ομιλία', listening: 'Ακούω...', send: 'Αποστολή',
  invalidFile: 'Μη έγκυρο αρχείο (μέγιστο 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Ανάλυσε αυτή τη φωτογραφία',
  noSignup: 'Χωρίς εγγραφή · Η πρώτη ερώτηση είναι δωρεάν',
  statsFree: 'Δωρεάν για να ξεκινήσεις · Χωρίς πιστωτική κάρτα · Διαθέσιμος 24/7',
  demoLabel: 'Ο Oli σε δράση',
  demoSubtitle: 'Ασθένειες, κλάδεμα, λίπανση, σχεδιασμός φύτευσης και πολλά άλλα',
  tabDiagnosis: '🔬 Διάγνωση', tabPlanning: '📐 Σχεδιασμός',
  confidence: 'βεβαιότητα', organic: '🌿 Βιολογικό', chemical: '🧪 Χημικό',
  agronomicData: 'Βασισμένο σε αγρονομικά δεδομένα',
  howLabel: 'Πώς λειτουργεί', howTitle: 'Τρία απλά βήματα',
  rolesLabel: 'Για κάθε ρόλο στη γεωργία',
  rolesTitle: 'Ο Oli απαντάει διαφορετικά σε κάθε χρήστη',
  rolesInstruction: 'Κάνε κλικ σε ρόλο για να δεις πραγματικές ερωτήσεις και απαντήσεις',
  tryAs: (r) => `Δοκίμασε ως ${r} →`,
  featuresHeading: 'Χαρακτηριστικά', testimonialsLabel: 'Τι λένε οι αγρότες',
  pricingLabel: 'Τιμολόγηση', pricingTitle: 'Ξεκίνα δωρεάν',
  pricingSubtitle: 'Αναβάθμισε όταν χρειαστείς περισσότερα',
  billingMonthly: 'Μηνιαία', billingAnnual: 'Ετήσια',
  perMonth: '/ μήνα', perYear: '/ χρόνο', noCreditCard: 'Χωρίς πιστωτική κάρτα', freeName: 'Starter',
  freeTagline: 'Για ερασιτέχνες κηπουρούς και νέους χρήστες',
  freeFeatures: ['20 ερωτήσεις / μήνα', 'Διάγνωση ασθένειας από φωτογραφία', 'Πλάνο θεραπείας με δόσεις', 'Ιστορικό παρεμβάσεων 7 ημερών', '1 αναφορά χωραφιού / μήνα', 'Έως 3 χωράφια', 'Υπενθυμίσεις από chat'],
  getStartedFree: 'Ξεκίνα δωρεάν',
  proYearlyNote: 'ή €49 / χρόνο — εξοικονομείς 18%',
  proTwoYearNote: 'ή €79 για 2 χρόνια — καλύτερη αξία',
  proTagline: 'Για αγρότες και παραγωγούς που εξαρτώνται από τη γη τους',
  proFeatures: ['Απεριόριστες ερωτήσεις', 'Απεριόριστα χωράφια + μνήμη καλλιεργειών', 'Πλήρες ιστορικό παρεμβάσεων', 'Υπολογισμοί άρδευσης και φύτευσης', 'Απεριόριστες PDF αναφορές χωραφιών', 'Υπενθυμίσεις από chat', 'Έξυπνες ειδοποιήσεις καιρού'],
  tryPro: 'Δοκίμασε Pro',
  agronomistName: 'Master', agronomistBadge: 'Για επαγγελματίες',
  agronomistYearlyNote: 'ή €490 / χρόνο — εξοικονομείς 17%',
  agronomistTwoYearNote: 'ή €790 για 2 χρόνια — καλύτερη αξία',
  agronomistTagline: 'Για γεωπόνους που συμβουλεύουν πελάτες',
  agronomistFeatures: ['Όλα του Pro', 'Διαχείριση απεριόριστων πελατών', 'Χωράφια & ιστορικό παρεμβάσεων ανά πελάτη', 'Επιστημονικοί υπολογισμοί (ETc, NPK)', 'Επώνυμες PDF αναφορές για πελάτες', 'Υπενθυμίσεις από chat'],
  startAgronomist: 'Ξεκίνα ως Master',
  enterpriseBadge: 'Προσαρμοσμένο', enterpriseContact: 'Κατόπιν επικοινωνίας',
  enterpriseSubtitle: 'Για συνεταιρισμούς & εταιρείες που διαχειρίζονται γεωπόνους',
  enterpriseFeatures: ['Όλα του Master', 'Πολλαπλοί χρήστες / ομάδα', 'White-label ή co-branded αναφορές', 'Προτεραιότητα υποστήριξης', 'Προσαρμοσμένες ενσωματώσεις κατόπιν αιτήματος', 'Υπενθυμίσεις από chat'],
  getInTouch: 'Επικοινωνήστε μαζί μας',
  ctaHeadline: 'Σταμάτα να μαντεύεις.', ctaBody: 'Ο Oli είναι δωρεάν για να ξεκινήσεις. Χωρίς εγγραφή, χωρίς πιστωτική κάρτα.',
  trialBadge: 'Δοκίμασε το Pro δωρεάν για 30 μέρες',
  ctaButton: 'Δοκίμασε τον Oli τώρα', ctaFine: 'Δωρεάν · Χωρίς πιστωτική κάρτα · Πάντα διαθέσιμος',
  privacy: 'Πολιτική Απορρήτου', terms: 'Όροι Χρήσης',
  docTitle: 'Oli — Ο AI Γεωπόνος σου | 24/7 Συμβουλές Καλλιεργειών',
  metaDesc: 'Ο Oli είναι ο προσωπικός σου γεωπόνος. Διάγνωση ασθενειών, σχέδια θεραπείας, σχεδιασμός φύτευσης, άρδευση, αναστήλωση χωραφιών.',
  ogTitle: 'Oli — Ο AI Γεωπόνος σου 24/7', ogLocale: 'el_GR', speechLang: 'el-GR',
  askOli: 'Ρώτα τον Oli...',
};

const en: LandingT = {
  tryFree: 'Try free', openApp: 'Open app',
  heroBadge: 'Your AI Agronomist · 24/7',
  heroH1: ['Your personal agronomist.', 'With you 24/7.'],
  heroSubtitle: 'Diagnose diseases, plan your fields, set up irrigation, rehabilitate old groves. From planting to harvest, Oli learns your crops.',
  heroPlaceholder: 'Ask or upload a photo...',
  heroPlaceholderHint: '(Shift+Enter for new line)',
  removePhoto: 'Remove photo', photoAttached: 'Photo attached',
  uploadPhoto: 'Upload photo', stopRecording: 'Stop recording',
  speak: 'Speak', listening: 'Listening...', send: 'Send',
  invalidFile: 'Invalid file (max 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analyze this photo',
  noSignup: 'No sign-up required · First question is free',
  statsFree: 'Free to start · No credit card · Available 24/7',
  demoLabel: 'Oli in action',
  demoSubtitle: 'Diseases, pruning, irrigation, planting plans and much more',
  tabDiagnosis: '🔬 Diagnosis', tabPlanning: '📐 Planning',
  confidence: 'confidence', organic: '🌿 Organic', chemical: '🧪 Chemical',
  agronomicData: 'Based on agronomic data',
  howLabel: 'How it works', howTitle: 'Three simple steps',
  rolesLabel: 'For every role in agriculture',
  rolesTitle: 'Oli tailors every answer to who is asking',
  rolesInstruction: 'Select a role to see real questions and answers',
  tryAs: (r) => `Try as ${r} →`,
  featuresHeading: 'Features', testimonialsLabel: 'What farmers say',
  pricingLabel: 'Pricing', pricingTitle: 'Start for free',
  pricingSubtitle: 'Upgrade when you need more',
  billingMonthly: 'Monthly', billingAnnual: 'Annual',
  perMonth: '/ month', perYear: '/ year', noCreditCard: 'No credit card required', freeName: 'Starter',
  freeTagline: 'For hobby gardeners & curious growers',
  freeFeatures: ['20 questions / month', 'Photo disease diagnosis', 'Treatment plan with dosages', '7-day intervention history', '1 field report per month', 'Up to 3 fields', 'Chat-triggered reminders'],
  getStartedFree: 'Get started free',
  proYearlyNote: 'or €49 / year — save 18%',
  proTwoYearNote: 'or €79 for 2 years — best value',
  proTagline: 'For farmers and growers who depend on their crops',
  proFeatures: ['Unlimited questions', 'Unlimited fields + crop memory', 'Full intervention history', 'Irrigation & planting calculations', 'Unlimited field PDF reports', 'Chat-triggered reminders', 'Smart weather alerts'],
  tryPro: 'Try Pro',
  agronomistName: 'Master', agronomistBadge: 'For professionals',
  agronomistYearlyNote: 'or €490 / year — save 17%',
  agronomistTwoYearNote: 'or €790 for 2 years — best value',
  agronomistTagline: 'For agronomists advising multiple clients',
  agronomistFeatures: ['Everything in Pro', 'Manage unlimited clients', 'Per-client fields & intervention history', 'Scientific calculations (ETc, NPK)', 'Branded PDF reports for clients', 'Chat-triggered reminders'],
  startAgronomist: 'Start with Master',
  enterpriseBadge: 'Custom', enterpriseContact: 'Contact us',
  enterpriseSubtitle: 'For cooperatives & agribusinesses managing agronomist teams',
  enterpriseFeatures: ['Everything in Master', 'Multiple seats / team accounts', 'White-label or co-branded reports', 'Priority support', 'Custom integrations on request', 'Chat-triggered reminders'],
  getInTouch: 'Get in touch',
  ctaHeadline: 'Stop guessing.', ctaBody: 'Oli is free to start. No sign-up required, no credit card.',
  trialBadge: 'Try Pro free for 30 days',
  ctaButton: 'Try Oli now', ctaFine: 'Free to start · No credit card · Available 24/7',
  privacy: 'Privacy Policy', terms: 'Terms of Service',
  docTitle: 'Oli — Your AI Agronomist | Farming Advice 24/7',
  metaDesc: 'Oli is your personal agronomist. Diagnose crop diseases, plan your fields, set up irrigation, rehabilitate old groves. Always available, always learning.',
  ogTitle: 'Oli — Your AI Agronomist, 24/7', ogLocale: 'en_US', speechLang: 'en-US',
  askOli: 'Ask Oli...',
};

const it: LandingT = {
  tryFree: 'Prova gratis', openApp: 'Apri app',
  heroBadge: 'Il tuo Agronomo AI · 24/7',
  heroH1: ['Il tuo agronomo personale.', 'Sempre con te.'],
  heroSubtitle: "Diagnostica malattie, pianifica i campi, gestisci l'irrigazione, recupera terreni abbandonati. Dalla semina al raccolto, Oli impara le tue colture.",
  heroPlaceholder: 'Fai una domanda o carica una foto...',
  heroPlaceholderHint: '(Shift+Invio per nuova riga)',
  removePhoto: 'Rimuovi foto', photoAttached: 'Foto allegata',
  uploadPhoto: 'Carica foto', stopRecording: 'Interrompi registrazione',
  speak: 'Parla', listening: 'In ascolto...', send: 'Invia',
  invalidFile: 'File non valido (max 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analizza questa foto',
  noSignup: 'Nessuna registrazione · Prima domanda gratuita',
  statsFree: 'Gratis per iniziare · Nessuna carta di credito · Disponibile 24/7',
  demoLabel: 'Oli in azione',
  demoSubtitle: 'Malattie, potatura, irrigazione, pianificazione colture e molto altro',
  tabDiagnosis: '🔬 Diagnosi', tabPlanning: '📐 Pianificazione',
  confidence: 'affidabilità', organic: '🌿 Biologico', chemical: '🧪 Chimico',
  agronomicData: 'Basato su dati agronomici',
  howLabel: 'Come funziona', howTitle: 'Tre semplici passi',
  rolesLabel: 'Per ogni ruolo in agricoltura',
  rolesTitle: 'Oli adatta ogni risposta a chi fa la domanda',
  rolesInstruction: 'Seleziona un ruolo per vedere domande e risposte reali',
  tryAs: (r) => `Prova come ${r} →`,
  featuresHeading: 'Funzionalità', testimonialsLabel: 'Cosa dicono gli agricoltori',
  pricingLabel: 'Prezzi', pricingTitle: 'Inizia gratis',
  pricingSubtitle: 'Aggiorna quando hai bisogno di più',
  billingMonthly: 'Mensile', billingAnnual: 'Annuale',
  perMonth: '/ mese', perYear: '/ anno', noCreditCard: 'Nessuna carta di credito', freeName: 'Starter',
  freeTagline: 'Per giardinieri hobbisti e produttori curiosi',
  freeFeatures: ['20 domande / mese', 'Diagnosi malattie da foto', 'Piano di trattamento con dosaggi', 'Storico interventi 7 giorni', '1 rapporto campo al mese', 'Fino a 3 campi', 'Promemoria via chat'],
  getStartedFree: 'Inizia gratis',
  proYearlyNote: 'o €49 / anno — risparmia 18%',
  proTwoYearNote: 'o €79 per 2 anni — miglior valore',
  proTagline: 'Per agricoltori e produttori che dipendono dai loro raccolti',
  proFeatures: ['Domande illimitate', 'Campi illimitati + memoria colture', 'Storico interventi completo', 'Calcoli irrigazione e piantagione', 'Rapporti PDF illimitati per campo', 'Promemoria via chat', 'Avvisi meteo intelligenti'],
  tryPro: 'Prova Pro',
  agronomistName: 'Master', agronomistBadge: 'Per professionisti',
  agronomistYearlyNote: 'o €490 / anno — risparmia 17%',
  agronomistTwoYearNote: 'o €790 per 2 anni — miglior valore',
  agronomistTagline: 'Per agronomi che seguono più clienti',
  agronomistFeatures: ['Tutto incluso in Pro', 'Gestione clienti illimitati', 'Campi e storico interventi per cliente', 'Calcoli scientifici (ETc, NPK)', 'Rapporti PDF personalizzati per i clienti', 'Promemoria via chat'],
  startAgronomist: 'Inizia con Master',
  enterpriseBadge: 'Personalizzato', enterpriseContact: 'Contattaci',
  enterpriseSubtitle: 'Per cooperative e aziende che gestiscono team di agronomi',
  enterpriseFeatures: ['Tutto incluso in Master', 'Più postazioni / account team', 'Report white-label o co-branded', 'Supporto prioritario', 'Integrazioni personalizzate su richiesta', 'Promemoria via chat'],
  getInTouch: 'Contattaci',
  ctaHeadline: 'Smettila di indovinare.', ctaBody: 'Oli è gratis per iniziare. Nessuna registrazione, nessuna carta di credito.',
  trialBadge: 'Prova Pro gratis per 30 giorni',
  ctaButton: 'Prova Oli adesso', ctaFine: 'Gratis · Nessuna carta · Disponibile 24/7',
  privacy: 'Privacy', terms: 'Termini',
  docTitle: 'Oli — Il tuo Agronomo AI | Consulenza Agricola 24/7',
  metaDesc: "Oli è il tuo agronomo personale. Diagnosi malattie, pianifica i campi, gestisci l'irrigazione. Sempre disponibile, impara sempre.",
  ogTitle: 'Oli — Il tuo Agronomo AI, 24/7', ogLocale: 'it_IT', speechLang: 'it-IT',
  askOli: 'Chiedi a Oli...',
};

const es: LandingT = {
  tryFree: 'Prueba gratis', openApp: 'Abrir app',
  heroBadge: 'Tu Agrónomo IA · 24/7',
  heroH1: ['Tu agrónomo personal.', 'Siempre a tu lado.'],
  heroSubtitle: 'Diagnóstico de enfermedades, planificación de cultivos, riego, rehabilitación de fincas. De la siembra a la cosecha, Oli aprende tus cultivos.',
  heroPlaceholder: 'Haz una pregunta o sube una foto...',
  heroPlaceholderHint: '(Shift+Intro para nueva línea)',
  removePhoto: 'Eliminar foto', photoAttached: 'Foto adjuntada',
  uploadPhoto: 'Subir foto', stopRecording: 'Detener grabación',
  speak: 'Hablar', listening: 'Escuchando...', send: 'Enviar',
  invalidFile: 'Archivo no válido (máx 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analizar esta foto',
  noSignup: 'Sin registro · Primera pregunta gratis',
  statsFree: 'Gratis para empezar · Sin tarjeta de crédito · Disponible 24/7',
  demoLabel: 'Oli en acción',
  demoSubtitle: 'Enfermedades, poda, riego, planificación de cultivos y mucho más',
  tabDiagnosis: '🔬 Diagnóstico', tabPlanning: '📐 Planificación',
  confidence: 'confianza', organic: '🌿 Ecológico', chemical: '🧪 Químico',
  agronomicData: 'Basado en datos agronómicos',
  howLabel: 'Cómo funciona', howTitle: 'Tres pasos simples',
  rolesLabel: 'Para cada rol en la agricultura',
  rolesTitle: 'Oli adapta cada respuesta a quien pregunta',
  rolesInstruction: 'Selecciona un rol para ver preguntas y respuestas reales',
  tryAs: (r) => `Probar como ${r} →`,
  featuresHeading: 'Características', testimonialsLabel: 'Lo que dicen los agricultores',
  pricingLabel: 'Precios', pricingTitle: 'Empieza gratis',
  pricingSubtitle: 'Mejora tu plan cuando necesites más',
  billingMonthly: 'Mensual', billingAnnual: 'Anual',
  perMonth: '/ mes', perYear: '/ año', noCreditCard: 'Sin tarjeta de crédito', freeName: 'Starter',
  freeTagline: 'Para jardineros aficionados y productores curiosos',
  freeFeatures: ['20 preguntas / mes', 'Diagnóstico de enfermedades por foto', 'Plan de tratamiento con dosis', 'Historial de intervenciones 7 días', '1 informe de campo al mes', 'Hasta 3 campos', 'Recordatorios por chat'],
  getStartedFree: 'Empezar gratis',
  proYearlyNote: 'o €49 / año — ahorra 18%',
  proTwoYearNote: 'o €79 por 2 años — mejor valor',
  proTagline: 'Para agricultores y productores que dependen de sus cultivos',
  proFeatures: ['Preguntas ilimitadas', 'Campos ilimitados + memoria de cultivos', 'Historial de intervenciones completo', 'Cálculos de riego y siembra', 'Informes PDF ilimitados por campo', 'Recordatorios por chat', 'Alertas meteorológicas inteligentes'],
  tryPro: 'Probar Pro',
  agronomistName: 'Master', agronomistBadge: 'Para profesionales',
  agronomistYearlyNote: 'o €490 / año — ahorra 17%',
  agronomistTwoYearNote: 'o €790 por 2 años — mejor valor',
  agronomistTagline: 'Para agrónomos que asesoran a múltiples clientes',
  agronomistFeatures: ['Todo incluido en Pro', 'Gestión de clientes ilimitados', 'Campos e historial de intervenciones por cliente', 'Cálculos científicos (ETc, NPK)', 'Informes PDF personalizados para clientes', 'Recordatorios por chat'],
  startAgronomist: 'Empezar con Master',
  enterpriseBadge: 'Personalizado', enterpriseContact: 'Contáctanos',
  enterpriseSubtitle: 'Para cooperativas y agronegocios que gestionan equipos de agrónomos',
  enterpriseFeatures: ['Todo incluido en Master', 'Múltiples puestos / cuentas de equipo', 'Informes white-label o co-branded', 'Soporte prioritario', 'Integraciones personalizadas bajo petición', 'Recordatorios por chat'],
  getInTouch: 'Contáctanos',
  ctaHeadline: 'Deja de adivinar.', ctaBody: 'Oli es gratis para empezar. Sin registro, sin tarjeta de crédito.',
  trialBadge: 'Prueba Pro gratis 30 días',
  ctaButton: 'Prueba Oli ahora', ctaFine: 'Gratis · Sin tarjeta · Disponible 24/7',
  privacy: 'Privacidad', terms: 'Términos',
  docTitle: 'Oli — Tu Agrónomo IA | Asesoramiento Agrícola 24/7',
  metaDesc: 'Oli es tu agrónomo personal. Diagnóstico de enfermedades, planifica tus campos, gestiona el riego. Siempre disponible, siempre aprendiendo.',
  ogTitle: 'Oli — Tu Agrónomo IA, 24/7', ogLocale: 'es_ES', speechLang: 'es-ES',
  askOli: 'Pregunta a Oli...',
};

const fr: LandingT = {
  tryFree: 'Essai gratuit', openApp: "Ouvrir l'app",
  heroBadge: 'Ton Agronome IA · 24/7',
  heroH1: ['Ton agronome personnel.', 'Toujours avec toi.'],
  heroSubtitle: "Diagnostic des maladies, planification des cultures, irrigation, réhabilitation des champs. De la plantation à la récolte, Oli apprend tes cultures.",
  heroPlaceholder: 'Pose une question ou charge une photo...',
  heroPlaceholderHint: '(Maj+Entrée pour nouvelle ligne)',
  removePhoto: 'Supprimer la photo', photoAttached: 'Photo jointe',
  uploadPhoto: 'Charger une photo', stopRecording: "Arrêter l'enregistrement",
  speak: 'Parler', listening: "J'écoute...", send: 'Envoyer',
  invalidFile: 'Fichier invalide (max 10Mo, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analyser cette photo',
  noSignup: 'Sans inscription · Première question gratuite',
  statsFree: 'Gratuit pour commencer · Sans carte bancaire · Disponible 24/7',
  demoLabel: 'Oli en action',
  demoSubtitle: 'Maladies, taille, irrigation, planification des cultures et bien plus',
  tabDiagnosis: '🔬 Diagnostic', tabPlanning: '📐 Planification',
  confidence: 'confiance', organic: '🌿 Biologique', chemical: '🧪 Chimique',
  agronomicData: 'Basé sur des données agronomiques',
  howLabel: 'Comment ça marche', howTitle: 'Trois étapes simples',
  rolesLabel: "Pour chaque rôle dans l'agriculture",
  rolesTitle: 'Oli adapte chaque réponse à qui pose la question',
  rolesInstruction: 'Sélectionne un rôle pour voir de vraies questions et réponses',
  tryAs: (r) => `Essayer en tant que ${r} →`,
  featuresHeading: 'Fonctionnalités', testimonialsLabel: 'Ce que disent les agriculteurs',
  pricingLabel: 'Tarifs', pricingTitle: 'Commence gratuitement',
  pricingSubtitle: "Passe à un plan supérieur si tu as besoin de plus",
  billingMonthly: 'Mensuel', billingAnnual: 'Annuel',
  perMonth: '/ mois', perYear: '/ an', noCreditCard: 'Sans carte bancaire', freeName: 'Starter',
  freeTagline: 'Pour les jardiniers amateurs et producteurs curieux',
  freeFeatures: ['20 questions / mois', 'Diagnostic maladie par photo', 'Plan de traitement avec dosages', 'Historique des interventions 7 jours', '1 rapport de champ par mois', "Jusqu'à 3 champs", 'Rappels via chat'],
  getStartedFree: 'Commencer gratuitement',
  proYearlyNote: 'ou 49€ / an — économise 18%',
  proTwoYearNote: 'ou 79€ pour 2 ans — meilleur rapport',
  proTagline: 'Pour les agriculteurs et producteurs qui dépendent de leurs cultures',
  proFeatures: ['Questions illimitées', 'Champs illimités + mémoire cultures', 'Historique des interventions complet', 'Calculs irrigation et plantation', 'Rapports PDF illimités par champ', 'Rappels via chat', 'Alertes météo intelligentes'],
  tryPro: 'Essayer Pro',
  agronomistName: 'Master', agronomistBadge: 'Pour les professionnels',
  agronomistYearlyNote: 'ou 490€ / an — économise 17%',
  agronomistTwoYearNote: 'ou 790€ pour 2 ans — meilleur rapport',
  agronomistTagline: 'Pour les agronomes conseillant plusieurs clients',
  agronomistFeatures: ['Tout inclus dans Pro', 'Gestion de clients illimités', 'Champs et historique des interventions par client', 'Calculs scientifiques (ETc, NPK)', 'Rapports PDF personnalisés pour les clients', 'Rappels via chat'],
  startAgronomist: 'Commencer avec Master',
  enterpriseBadge: 'Sur mesure', enterpriseContact: 'Nous contacter',
  enterpriseSubtitle: "Pour les coopératives et agro-entreprises gérant des équipes d'agronomes",
  enterpriseFeatures: ['Tout inclus dans Master', 'Plusieurs sièges / comptes équipe', 'Rapports white-label ou co-brandés', 'Support prioritaire', 'Intégrations personnalisées sur demande', 'Rappels via chat'],
  getInTouch: 'Nous contacter',
  ctaHeadline: 'Arrête de deviner.', ctaBody: 'Oli est gratuit pour commencer. Sans inscription, sans carte bancaire.',
  trialBadge: 'Essai Pro gratuit 30 jours',
  ctaButton: 'Essayer Oli maintenant', ctaFine: 'Gratuit · Sans carte · Disponible 24/7',
  privacy: 'Confidentialité', terms: 'Conditions',
  docTitle: 'Oli — Ton Agronome IA | Conseils Agricoles 24/7',
  metaDesc: "Oli est ton agronome personnel. Diagnostic des maladies, planifie tes champs, gère l'irrigation. Toujours disponible, toujours en apprentissage.",
  ogTitle: 'Oli — Ton Agronome IA, 24/7', ogLocale: 'fr_FR', speechLang: 'fr-FR',
  askOli: 'Demande à Oli...',
};

const ar: LandingT = {
  tryFree: 'جرّب مجانًا', openApp: 'افتح التطبيق',
  heroBadge: 'مستشارك الزراعي الذكي · 24/7',
  heroH1: ['مستشارك الزراعي الشخصي.', 'معك في كل وقت.'],
  heroSubtitle: 'تشخيص الأمراض، تخطيط الحقول، إدارة الري، تأهيل البساتين. من البذر حتى الحصاد، يتعلم أولي محاصيلك.',
  heroPlaceholder: 'اطرح سؤالًا أو ارفع صورة...',
  heroPlaceholderHint: '(Shift+Enter لسطر جديد)',
  removePhoto: 'حذف الصورة', photoAttached: 'تم إرفاق الصورة',
  uploadPhoto: 'رفع صورة', stopRecording: 'إيقاف التسجيل',
  speak: 'تحدث', listening: 'أستمع...', send: 'إرسال',
  invalidFile: 'ملف غير صالح (الحد الأقصى 10MB، JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'تحليل هذه الصورة',
  noSignup: 'بدون تسجيل · السؤال الأول مجاني',
  statsFree: 'مجاني للبدء · بدون بطاقة ائتمان · متاح 24/7',
  demoLabel: 'أولي في العمل',
  demoSubtitle: 'الأمراض، التقليم، الري، تخطيط الزراعة وأكثر بكثير',
  tabDiagnosis: '🔬 تشخيص', tabPlanning: '📐 تخطيط',
  confidence: 'دقة', organic: '🌿 عضوي', chemical: '🧪 كيميائي',
  agronomicData: 'مبني على بيانات زراعية',
  howLabel: 'كيف يعمل', howTitle: 'ثلاث خطوات بسيطة',
  rolesLabel: 'لكل دور في الزراعة',
  rolesTitle: 'أولي يكيّف كل إجابة حسب من يسأل',
  rolesInstruction: 'اختر دورًا لترى أسئلة وإجابات حقيقية',
  tryAs: (r) => `جرّب كـ${r} →`,
  featuresHeading: 'المميزات', testimonialsLabel: 'ما يقوله المزارعون',
  pricingLabel: 'الأسعار', pricingTitle: 'ابدأ مجانًا',
  pricingSubtitle: 'طوّر خطتك عندما تحتاج أكثر',
  billingMonthly: 'شهري', billingAnnual: 'سنوي',
  perMonth: '/ شهر', perYear: '/ سنة', noCreditCard: 'بدون بطاقة ائتمان', freeName: 'Starter',
  freeTagline: 'للبستانيين الهواة والمنتجين الفضوليين',
  freeFeatures: ['20 سؤال / شهر', 'تشخيص أمراض المحاصيل من صورة', 'خطة علاج بالجرعات', 'سجل التدخلات 7 أيام', 'تقرير حقل واحد / شهر', 'حتى 3 حقول', 'تذكيرات عبر الدردشة'],
  getStartedFree: 'ابدأ مجانًا',
  proYearlyNote: 'أو 49€ / سنة — وفّر 18%',
  proTwoYearNote: 'أو 79€ لسنتين — أفضل قيمة',
  proTagline: 'للمزارعين والمنتجين الذين يعتمدون على محاصيلهم',
  proFeatures: ['أسئلة غير محدودة', 'حقول غير محدودة + ذاكرة المحاصيل', 'سجل تدخلات كامل', 'حسابات الري والزراعة', 'تقارير PDF غير محدودة للحقول', 'تذكيرات عبر الدردشة', 'تنبيهات طقس ذكية'],
  tryPro: 'جرّب Pro',
  agronomistName: 'Master', agronomistBadge: 'للمحترفين',
  agronomistYearlyNote: 'أو 490€ / سنة — وفّر 17%',
  agronomistTwoYearNote: 'أو 790€ لسنتين — أفضل قيمة',
  agronomistTagline: 'للمهندسين الزراعيين الذين يستشيرون عدة عملاء',
  agronomistFeatures: ['كل ما في Pro', 'إدارة عملاء غير محدودين', 'حقول وسجل تدخلات لكل عميل', 'حسابات علمية (ETc, NPK)', 'تقارير PDF مخصصة للعملاء', 'تذكيرات عبر الدردشة'],
  startAgronomist: 'ابدأ مع Master',
  enterpriseBadge: 'مخصص', enterpriseContact: 'تواصل معنا',
  enterpriseSubtitle: 'للتعاونيات والشركات الزراعية التي تدير فرق المهندسين الزراعيين',
  enterpriseFeatures: ['كل ما في Master', 'مقاعد متعددة / حسابات الفريق', 'تقارير white-label أو co-branded', 'دعم ذو أولوية', 'تكاملات مخصصة عند الطلب', 'تذكيرات عبر الدردشة'],
  getInTouch: 'تواصل معنا',
  ctaHeadline: 'توقف عن التخمين.', ctaBody: 'أولي مجاني للبدء. بدون تسجيل، بدون بطاقة ائتمان.',
  trialBadge: 'جرّب Pro مجانًا لمدة 30 يومًا',
  ctaButton: 'جرّب أولي الآن', ctaFine: 'مجاني · بدون بطاقة · متاح 24/7',
  privacy: 'الخصوصية', terms: 'الشروط',
  docTitle: 'Oli — مستشارك الزراعي الذكي | نصائح زراعية 24/7',
  metaDesc: 'أولي هو مستشارك الزراعي الشخصي. تشخيص أمراض المحاصيل، تخطيط حقولك، إدارة الري. متاح دائمًا، يتعلم دائمًا.',
  ogTitle: 'Oli — مستشارك الزراعي الذكي، 24/7', ogLocale: 'ar_SA', speechLang: 'ar-SA',
  askOli: 'اسأل أولي...',
};

const tr: LandingT = {
  tryFree: 'Ücretsiz dene', openApp: 'Uygulamayı aç',
  heroBadge: 'AI Tarım Danışmanın · 24/7',
  heroH1: ['Kişisel tarım danışmanın.', '7/24 yanında.'],
  heroSubtitle: 'Hastalık teşhisi, tarla planlaması, sulama yönetimi, bahçe yenileme. Ekimden hasada, Oli kültürlerini öğrenir.',
  heroPlaceholder: 'Soru sor veya fotoğraf yükle...',
  heroPlaceholderHint: '(Shift+Enter yeni satır için)',
  removePhoto: 'Fotoğrafı kaldır', photoAttached: 'Fotoğraf eklendi',
  uploadPhoto: 'Fotoğraf yükle', stopRecording: 'Kaydı durdur',
  speak: 'Konuş', listening: 'Dinliyorum...', send: 'Gönder',
  invalidFile: 'Geçersiz dosya (maks 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Bu fotoğrafı analiz et',
  noSignup: 'Kayıt gerekmez · İlk soru ücretsiz',
  statsFree: 'Başlamak ücretsiz · Kredi kartı gerekmez · 7/24 müsait',
  demoLabel: 'Oli iş başında',
  demoSubtitle: 'Hastalıklar, budama, sulama, ekim planlaması ve çok daha fazlası',
  tabDiagnosis: '🔬 Teşhis', tabPlanning: '📐 Planlama',
  confidence: 'güven', organic: '🌿 Organik', chemical: '🧪 Kimyasal',
  agronomicData: 'Agronomi verilerine dayalı',
  howLabel: 'Nasıl çalışır', howTitle: 'Üç basit adım',
  rolesLabel: 'Tarımdaki her rol için',
  rolesTitle: 'Oli her soruyu soran kişiye göre yanıtlar',
  rolesInstruction: 'Gerçek soru ve yanıtları görmek için bir rol seç',
  tryAs: (r) => `${r} olarak dene →`,
  featuresHeading: 'Özellikler', testimonialsLabel: 'Çiftçiler ne diyor',
  pricingLabel: 'Fiyatlandırma', pricingTitle: 'Ücretsiz başla',
  pricingSubtitle: 'Daha fazlasına ihtiyaç duyunca yükselt',
  billingMonthly: 'Aylık', billingAnnual: 'Yıllık',
  perMonth: '/ ay', perYear: '/ yıl', noCreditCard: 'Kredi kartı gerekmez', freeName: 'Starter',
  freeTagline: 'Hobi bahçıvanları ve meraklı yetiştiriciler için',
  freeFeatures: ['20 soru / ay', 'Fotoğrafla hastalık teşhisi', 'Dozajlı tedavi planı', '7 günlük müdahale geçmişi', 'Ayda 1 tarla raporu', 'En fazla 3 tarla', 'Sohbet hatırlatıcıları'],
  getStartedFree: 'Ücretsiz başla',
  proYearlyNote: 'veya €49 / yıl — %18 tasarruf',
  proTwoYearNote: 'veya €79 / 2 yıl — en iyi değer',
  proTagline: 'Hasatlarına bağımlı çiftçiler ve üreticiler için',
  proFeatures: ['Sınırsız soru', 'Sınırsız tarla + kültür hafızası', 'Tam müdahale geçmişi', 'Sulama ve ekim hesaplamaları', 'Sınırsız PDF tarla raporu', 'Sohbet hatırlatıcıları', 'Akıllı hava uyarıları'],
  tryPro: 'Pro\'yu dene',
  agronomistName: 'Master', agronomistBadge: 'Profesyoneller için',
  agronomistYearlyNote: 'veya €490 / yıl — %17 tasarruf',
  agronomistTwoYearNote: 'veya €790 / 2 yıl — en iyi değer',
  agronomistTagline: 'Birden fazla müşteriye danışmanlık yapan tarım mühendisleri için',
  agronomistFeatures: ['Pro\'daki her şey', 'Sınırsız müşteri yönetimi', 'Müşteri başına tarla ve müdahale geçmişi', 'Bilimsel hesaplamalar (ETc, NPK)', 'Müşteriler için markalı PDF raporları', 'Sohbet hatırlatıcıları'],
  startAgronomist: 'Master ile başla',
  enterpriseBadge: 'Özel', enterpriseContact: 'Bize ulaşın',
  enterpriseSubtitle: 'Tarım mühendisi ekiplerini yöneten kooperatifler ve şirketler için',
  enterpriseFeatures: ['Master\'daki her şey', 'Birden fazla kullanıcı / ekip hesabı', 'White-label veya co-branded raporlar', 'Öncelikli destek', 'Talep üzerine özel entegrasyonlar', 'Sohbet hatırlatıcıları'],
  getInTouch: 'Bize ulaşın',
  ctaHeadline: 'Tahmin etmeyi bırak.', ctaBody: 'Oli ücretsiz başlamak için. Kayıt gerekmez, kredi kartı gerekmez.',
  trialBadge: '30 gün Pro ücretsiz dene',
  ctaButton: 'Oli\'yi şimdi dene', ctaFine: 'Ücretsiz · Kart gerekmez · 7/24 müsait',
  privacy: 'Gizlilik', terms: 'Koşullar',
  docTitle: 'Oli — AI Tarım Danışmanın | 7/24 Tarım Tavsiyesi',
  metaDesc: 'Oli kişisel tarım danışmanındır. Hastalık teşhisi, tarla planlaması, sulama yönetimi. Her zaman mevcut, sürekli öğreniyor.',
  ogTitle: 'Oli — AI Tarım Danışmanın, 7/24', ogLocale: 'tr_TR', speechLang: 'tr-TR',
  askOli: 'Oli\'ye sor...',
};

const ro: LandingT = {
  tryFree: 'Încearcă gratuit', openApp: 'Deschide app',
  heroBadge: 'Agronomul tău AI · 24/7',
  heroH1: ['Agronomul tău personal.', 'Mereu cu tine.'],
  heroSubtitle: 'Diagnostic boli, planificare câmpuri, irigare, reabilitare livezi. De la plantare la recoltare, Oli îți învață culturile.',
  heroPlaceholder: 'Pune o întrebare sau încarcă o fotografie...',
  heroPlaceholderHint: '(Shift+Enter pentru rând nou)',
  removePhoto: 'Șterge fotografia', photoAttached: 'Fotografie atașată',
  uploadPhoto: 'Încarcă fotografie', stopRecording: 'Oprește înregistrarea',
  speak: 'Vorbește', listening: 'Ascult...', send: 'Trimite',
  invalidFile: 'Fișier invalid (max 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analizează această fotografie',
  noSignup: 'Fără înregistrare · Prima întrebare gratuită',
  statsFree: 'Gratuit pentru a începe · Fără card · Disponibil 24/7',
  demoLabel: 'Oli în acțiune',
  demoSubtitle: 'Boli, tăieri, irigare, planificare culturi și mult mai mult',
  tabDiagnosis: '🔬 Diagnostic', tabPlanning: '📐 Planificare',
  confidence: 'încredere', organic: '🌿 Bio', chemical: '🧪 Chimic',
  agronomicData: 'Bazat pe date agronomice',
  howLabel: 'Cum funcționează', howTitle: 'Trei pași simpli',
  rolesLabel: 'Pentru fiecare rol în agricultură',
  rolesTitle: 'Oli adaptează fiecare răspuns la cel care întreabă',
  rolesInstruction: 'Selectează un rol pentru a vedea întrebări și răspunsuri reale',
  tryAs: (r) => `Încearcă ca ${r} →`,
  featuresHeading: 'Caracteristici', testimonialsLabel: 'Ce spun fermierii',
  pricingLabel: 'Prețuri', pricingTitle: 'Începe gratuit',
  pricingSubtitle: 'Fă upgrade când ai nevoie de mai mult',
  billingMonthly: 'Lunar', billingAnnual: 'Anual',
  perMonth: '/ lună', perYear: '/ an', noCreditCard: 'Fără card de credit', freeName: 'Starter',
  freeTagline: 'Pentru grădinari amatori și crescători curioși',
  freeFeatures: ['20 întrebări / lună', 'Diagnostic boli din foto', 'Plan de tratament cu doze', 'Istoric intervenții 7 zile', '1 raport câmp / lună', 'Până la 3 câmpuri', 'Mementouri prin chat'],
  getStartedFree: 'Începe gratuit',
  proYearlyNote: 'sau €49 / an — economisești 18%',
  proTwoYearNote: 'sau €79 pentru 2 ani — cea mai bună valoare',
  proTagline: 'Pentru fermieri și producători care depind de culturile lor',
  proFeatures: ['Întrebări nelimitate', 'Câmpuri nelimitate + memorie culturi', 'Istoric complet intervenții', 'Calcule irigare și plantare', 'Rapoarte PDF nelimitate per câmp', 'Mementouri prin chat', 'Alerte meteo inteligente'],
  tryPro: 'Încearcă Pro',
  agronomistName: 'Master', agronomistBadge: 'Pentru profesioniști',
  agronomistYearlyNote: 'sau €490 / an — economisești 17%',
  agronomistTwoYearNote: 'sau €790 pentru 2 ani — cea mai bună valoare',
  agronomistTagline: 'Pentru agronomi care consiliază mai mulți clienți',
  agronomistFeatures: ['Tot ce include Pro', 'Gestionare clienți nelimitați', 'Câmpuri și istoric per client', 'Calcule științifice (ETc, NPK)', 'Rapoarte PDF personalizate pentru clienți', 'Mementouri prin chat'],
  startAgronomist: 'Începe cu Master',
  enterpriseBadge: 'Personalizat', enterpriseContact: 'Contactează-ne',
  enterpriseSubtitle: 'Pentru cooperative și companii care gestionează echipe de agronomi',
  enterpriseFeatures: ['Tot ce include Master', 'Locuri multiple / conturi echipă', 'Rapoarte white-label sau co-branded', 'Suport prioritar', 'Integrări personalizate la cerere', 'Mementouri prin chat'],
  getInTouch: 'Contactează-ne',
  ctaHeadline: 'Nu mai ghici.', ctaBody: 'Oli este gratuit pentru a începe. Fără înregistrare, fără card.',
  trialBadge: 'Încearcă Pro gratuit 30 de zile',
  ctaButton: 'Încearcă Oli acum', ctaFine: 'Gratuit · Fără card · Disponibil 24/7',
  privacy: 'Confidențialitate', terms: 'Termeni',
  docTitle: 'Oli — Agronomul tău AI | Sfaturi Agricole 24/7',
  metaDesc: 'Oli este agronomul tău personal. Diagnostic boli, planificare câmpuri, irigare. Mereu disponibil, mereu în învățare.',
  ogTitle: 'Oli — Agronomul tău AI, 24/7', ogLocale: 'ro_RO', speechLang: 'ro-RO',
  askOli: 'Întreabă Oli...',
};

const bg: LandingT = {
  tryFree: 'Опитай безплатно', openApp: 'Отвори приложението',
  heroBadge: 'Твоят AI Агроном · 24/7',
  heroH1: ['Твоят личен агроном.', 'Винаги с теб.'],
  heroSubtitle: 'Диагностика на болести, планиране на ниви, напояване, рехабилитация на градини. От засяване до жътва, Oli учи твоите култури.',
  heroPlaceholder: 'Задай въпрос или качи снимка...',
  heroPlaceholderHint: '(Shift+Enter за нов ред)',
  removePhoto: 'Премахни снимката', photoAttached: 'Снимката е прикачена',
  uploadPhoto: 'Качи снимка', stopRecording: 'Спри записа',
  speak: 'Говори', listening: 'Слушам...', send: 'Изпрати',
  invalidFile: 'Невалиден файл (макс 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Анализирай тази снимка',
  noSignup: 'Без регистрация · Първият въпрос е безплатен',
  statsFree: 'Безплатно за начало · Без карта · Достъпен 24/7',
  demoLabel: 'Oli в действие',
  demoSubtitle: 'Болести, кастрене, напояване, планиране на засяването и много повече',
  tabDiagnosis: '🔬 Диагноза', tabPlanning: '📐 Планиране',
  confidence: 'увереност', organic: '🌿 Органично', chemical: '🧪 Химично',
  agronomicData: 'Базирано на агрономически данни',
  howLabel: 'Как работи', howTitle: 'Три прости стъпки',
  rolesLabel: 'За всяка роля в земеделието',
  rolesTitle: 'Oli адаптира всеки отговор към питащия',
  rolesInstruction: 'Избери роля, за да видиш реални въпроси и отговори',
  tryAs: (r) => `Опитай като ${r} →`,
  featuresHeading: 'Функции', testimonialsLabel: 'Какво казват фермерите',
  pricingLabel: 'Цени', pricingTitle: 'Започни безплатно',
  pricingSubtitle: 'Надстрой когато имаш нужда от повече',
  billingMonthly: 'Месечно', billingAnnual: 'Годишно',
  perMonth: '/ месец', perYear: '/ год', noCreditCard: 'Без кредитна карта', freeName: 'Starter',
  freeTagline: 'За любители градинари и любопитни производители',
  freeFeatures: ['20 въпроса / месец', 'Диагноза болести по снимка', 'План за лечение с дози', 'История на намесите 7 дни', '1 доклад за нива / месец', 'До 3 ниви', 'Напомняния от чата'],
  getStartedFree: 'Започни безплатно',
  proYearlyNote: 'или €49 / год — спестяваш 18%',
  proTwoYearNote: 'или €79 за 2 год — най-добра стойност',
  proTagline: 'За фермери и производители, зависими от реколтата си',
  proFeatures: ['Неограничени въпроси', 'Неограничени ниви + памет на културите', 'Пълна история на намесите', 'Изчисления за напояване и засяване', 'Неограничени PDF доклади за ниви', 'Напомняния от чата', 'Умни метео сигнали'],
  tryPro: 'Опитай Pro',
  agronomistName: 'Master', agronomistBadge: 'За професионалисти',
  agronomistYearlyNote: 'или €490 / год — спестяваш 17%',
  agronomistTwoYearNote: 'или €790 за 2 год — най-добра стойност',
  agronomistTagline: 'За агрономи, консултиращи множество клиенти',
  agronomistFeatures: ['Всичко от Pro', 'Управление на неограничени клиенти', 'Ниви и история на намесите за всеки клиент', 'Научни изчисления (ETc, NPK)', 'Брандирани PDF доклади за клиенти', 'Напомняния от чата'],
  startAgronomist: 'Започни с Master',
  enterpriseBadge: 'По поръчка', enterpriseContact: 'Свържи се с нас',
  enterpriseSubtitle: 'За кооперации и агробизнеси, управляващи екипи от агрономи',
  enterpriseFeatures: ['Всичко от Master', 'Множество места / екипни акаунти', 'White-label или co-branded доклади', 'Приоритетна поддръжка', 'Персонализирани интеграции при заявка', 'Напомняния от чата'],
  getInTouch: 'Свържи се с нас',
  ctaHeadline: 'Спри да гадаеш.', ctaBody: 'Oli е безплатен за начало. Без регистрация, без карта.',
  trialBadge: 'Опитай Pro безплатно 30 дни',
  ctaButton: 'Опитай Oli сега', ctaFine: 'Безплатно · Без карта · Достъпен 24/7',
  privacy: 'Поверителност', terms: 'Условия',
  docTitle: 'Oli — Твоят AI Агроном | Земеделски Съвети 24/7',
  metaDesc: 'Oli е твоят личен агроном. Диагностика болести, планиране на ниви, напояване. Винаги на разположение, винаги учи.',
  ogTitle: 'Oli — Твоят AI Агроном, 24/7', ogLocale: 'bg_BG', speechLang: 'bg-BG',
  askOli: 'Питай Oli...',
};

const sq: LandingT = {
  tryFree: 'Provo falas', openApp: 'Hap aplikacionin',
  heroBadge: 'Agronomu yt AI · 24/7',
  heroH1: ['Agronomu yt personal.', 'Gjithmonë me ty.'],
  heroSubtitle: 'Diagnozë sëmundjesh, planifikim fushash, ujitje, rehabilitim kopshtesh. Nga mbjellja deri te korrja, Oli mëson kulturat e tua.',
  heroPlaceholder: 'Bëj pyetje ose ngarko foto...',
  heroPlaceholderHint: '(Shift+Enter për rresht të ri)',
  removePhoto: 'Hiq foton', photoAttached: 'Foto bashkëngjitur',
  uploadPhoto: 'Ngarko foto', stopRecording: 'Ndalo regjistrimin',
  speak: 'Fol', listening: 'Po dëgjoj...', send: 'Dërgo',
  invalidFile: 'Skedar i pavlefshëm (maks 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analizoje këtë foto',
  noSignup: 'Pa regjistrim · Pyetja e parë falas',
  statsFree: 'Falas për të filluar · Pa kartë krediti · Disponibël 24/7',
  demoLabel: 'Oli në veprim',
  demoSubtitle: 'Sëmundje, krasitje, ujitje, planifikim kulturash dhe shumë më tepër',
  tabDiagnosis: '🔬 Diagnozë', tabPlanning: '📐 Planifikim',
  confidence: 'besim', organic: '🌿 Organik', chemical: '🧪 Kimik',
  agronomicData: 'Bazuar në të dhëna agronomike',
  howLabel: 'Si funksionon', howTitle: 'Tre hapa të thjeshtë',
  rolesLabel: 'Për çdo rol në bujqësi',
  rolesTitle: 'Oli përshtat çdo përgjigje me atë që pyet',
  rolesInstruction: 'Zgjidh një rol për të parë pyetje dhe përgjigje reale',
  tryAs: (r) => `Provo si ${r} →`,
  featuresHeading: 'Karakteristika', testimonialsLabel: 'Çfarë thonë fermerët',
  pricingLabel: 'Çmimet', pricingTitle: 'Fillo falas',
  pricingSubtitle: 'Shto kur të duhet më shumë',
  billingMonthly: 'Mujor', billingAnnual: 'Vjetor',
  perMonth: '/ muaj', perYear: '/ vit', noCreditCard: 'Pa kartë krediti', freeName: 'Starter',
  freeTagline: 'Për kopshtarë hobistë dhe prodhues të kureshtarë',
  freeFeatures: ['20 pyetje / muaj', 'Diagnozë sëmundjesh nga foto', 'Plan trajtimi me doza', 'Historiku i ndërhyrjeve 7 ditë', '1 raport fushe / muaj', 'Deri në 3 fusha', 'Kujtesa nëpërmjet chatit'],
  getStartedFree: 'Fillo falas',
  proYearlyNote: 'ose €49 / vit — kursej 18%',
  proTwoYearNote: 'ose €79 për 2 vjet — vlera më e mirë',
  proTagline: 'Për fermerë dhe prodhues që varen nga kulturat e tyre',
  proFeatures: ['Pyetje të pakufizuara', 'Fusha të pakufizuara + kujtesë kulturash', 'Historik i plotë ndërhyrjesh', 'Llogaritje ujitjeje dhe mbjelljes', 'Raporte PDF të pakufizuara për fusha', 'Kujtesa nëpërmjet chatit', 'Alarme inteligjente të motit'],
  tryPro: 'Provo Pro',
  agronomistName: 'Master', agronomistBadge: 'Për profesionistët',
  agronomistYearlyNote: 'ose €490 / vit — kursej 17%',
  agronomistTwoYearNote: 'ose €790 për 2 vjet — vlera më e mirë',
  agronomistTagline: 'Për agronomë që këshillojnë klientë të shumtë',
  agronomistFeatures: ['Gjithçka nga Pro', 'Menaxhim klientësh të pakufizuar', 'Fusha dhe historiku i ndërhyrjeve për klient', 'Llogaritje shkencore (ETc, NPK)', 'Raporte PDF të markuara për klientët', 'Kujtesa nëpërmjet chatit'],
  startAgronomist: 'Fillo me Master',
  enterpriseBadge: 'Me porosi', enterpriseContact: 'Na kontakto',
  enterpriseSubtitle: 'Për kooperativa dhe kompani që menaxhojnë ekipe agronomësh',
  enterpriseFeatures: ['Gjithçka nga Master', 'Vende të shumta / llogari ekipi', 'Raporte white-label ose co-branded', 'Mbështetje prioritare', 'Integrime me porosi sipas kërkesës', 'Kujtesa nëpërmjet chatit'],
  getInTouch: 'Na kontakto',
  ctaHeadline: 'Mos gjasohu më.', ctaBody: 'Oli është falas për të filluar. Pa regjistrim, pa kartë krediti.',
  trialBadge: 'Provo Pro falas 30 ditë',
  ctaButton: 'Provo Oli tani', ctaFine: 'Falas · Pa kartë · Disponibël 24/7',
  privacy: 'Privatësia', terms: 'Kushtet',
  docTitle: 'Oli — Agronomu yt AI | Këshilla Bujqësore 24/7',
  metaDesc: 'Oli është agronomu yt personal. Diagnozë sëmundjesh, planifiko fushat, menaxho ujitjen. Gjithmonë disponibël, gjithmonë mëson.',
  ogTitle: 'Oli — Agronomu yt AI, 24/7', ogLocale: 'sq_AL', speechLang: 'sq-AL',
  askOli: 'Pyet Oli...',
};

const pt: LandingT = {
  tryFree: 'Experimenta grátis', openApp: 'Abrir app',
  heroBadge: 'O teu Agrónomo IA · 24/7',
  heroH1: ['O teu agrónomo pessoal.', 'Sempre contigo.'],
  heroSubtitle: 'Diagnóstico de doenças, planeamento de campos, irrigação, reabilitação de olivais. Da sementeira à colheita, o Oli aprende as tuas culturas.',
  heroPlaceholder: 'Faz uma pergunta ou carrega uma foto...',
  heroPlaceholderHint: '(Shift+Enter para nova linha)',
  removePhoto: 'Remover foto', photoAttached: 'Foto anexada',
  uploadPhoto: 'Carregar foto', stopRecording: 'Parar gravação',
  speak: 'Falar', listening: 'A ouvir...', send: 'Enviar',
  invalidFile: 'Ficheiro inválido (máx 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analisar esta foto',
  noSignup: 'Sem registo · Primeira pergunta grátis',
  statsFree: 'Grátis para começar · Sem cartão · Disponível 24/7',
  demoLabel: 'Oli em ação',
  demoSubtitle: 'Doenças, poda, irrigação, planeamento de culturas e muito mais',
  tabDiagnosis: '🔬 Diagnóstico', tabPlanning: '📐 Planeamento',
  confidence: 'confiança', organic: '🌿 Orgânico', chemical: '🧪 Químico',
  agronomicData: 'Baseado em dados agronómicos',
  howLabel: 'Como funciona', howTitle: 'Três passos simples',
  rolesLabel: 'Para cada papel na agricultura',
  rolesTitle: 'Oli adapta cada resposta a quem pergunta',
  rolesInstruction: 'Seleciona um papel para ver perguntas e respostas reais',
  tryAs: (r) => `Experimentar como ${r} →`,
  featuresHeading: 'Funcionalidades', testimonialsLabel: 'O que dizem os agricultores',
  pricingLabel: 'Preços', pricingTitle: 'Começa grátis',
  pricingSubtitle: 'Faz upgrade quando precisares de mais',
  billingMonthly: 'Mensal', billingAnnual: 'Anual',
  perMonth: '/ mês', perYear: '/ ano', noCreditCard: 'Sem cartão de crédito', freeName: 'Starter',
  freeTagline: 'Para jardineiros de lazer e produtores curiosos',
  freeFeatures: ['20 perguntas / mês', 'Diagnóstico de doenças por foto', 'Plano de tratamento com doses', 'Histórico de intervenções 7 dias', '1 relatório de campo por mês', 'Até 3 campos', 'Lembretes por chat'],
  getStartedFree: 'Começar grátis',
  proYearlyNote: 'ou €49 / ano — poupa 18%',
  proTwoYearNote: 'ou €79 por 2 anos — melhor valor',
  proTagline: 'Para agricultores e produtores que dependem das suas culturas',
  proFeatures: ['Perguntas ilimitadas', 'Campos ilimitados + memória de culturas', 'Histórico completo de intervenções', 'Cálculos de irrigação e plantação', 'Relatórios PDF ilimitados por campo', 'Lembretes por chat', 'Alertas meteorológicos inteligentes'],
  tryPro: 'Experimentar Pro',
  agronomistName: 'Master', agronomistBadge: 'Para profissionais',
  agronomistYearlyNote: 'ou €490 / ano — poupa 17%',
  agronomistTwoYearNote: 'ou €790 por 2 anos — melhor valor',
  agronomistTagline: 'Para agrónomos que aconselham múltiplos clientes',
  agronomistFeatures: ['Tudo incluído em Pro', 'Gestão de clientes ilimitados', 'Campos e histórico por cliente', 'Cálculos científicos (ETc, NPK)', 'Relatórios PDF personalizados para clientes', 'Lembretes por chat'],
  startAgronomist: 'Começar com Master',
  enterpriseBadge: 'Personalizado', enterpriseContact: 'Fale connosco',
  enterpriseSubtitle: 'Para cooperativas e agroempresas que gerem equipas de agrónomos',
  enterpriseFeatures: ['Tudo incluído em Master', 'Vários lugares / contas de equipa', 'Relatórios white-label ou co-branded', 'Suporte prioritário', 'Integrações personalizadas a pedido', 'Lembretes por chat'],
  getInTouch: 'Fale connosco',
  ctaHeadline: 'Para de adivinhar.', ctaBody: 'O Oli é grátis para começar. Sem registo, sem cartão de crédito.',
  trialBadge: 'Experimenta Pro grátis 30 dias',
  ctaButton: 'Experimenta o Oli agora', ctaFine: 'Grátis · Sem cartão · Disponível 24/7',
  privacy: 'Privacidade', terms: 'Termos',
  docTitle: 'Oli — O teu Agrónomo IA | Conselhos Agrícolas 24/7',
  metaDesc: 'O Oli é o teu agrónomo pessoal. Diagnóstico de doenças, planeia os teus campos, gere a irrigação. Sempre disponível, sempre a aprender.',
  ogTitle: 'Oli — O teu Agrónomo IA, 24/7', ogLocale: 'pt_PT', speechLang: 'pt-PT',
  askOli: 'Pergunta ao Oli...',
};

const de: LandingT = {
  tryFree: 'Kostenlos testen', openApp: 'App öffnen',
  heroBadge: 'Dein KI-Agrarberater · 24/7',
  heroH1: ['Dein persönlicher Agrarberater.', 'Immer für dich da.'],
  heroSubtitle: 'Krankheitsdiagnose, Feldplanung, Bewässerung, Sanierung alter Anlagen. Von der Aussaat bis zur Ernte lernt Oli deine Kulturen kennen.',
  heroPlaceholder: 'Frage stellen oder Foto hochladen...',
  heroPlaceholderHint: '(Shift+Enter für neue Zeile)',
  removePhoto: 'Foto entfernen', photoAttached: 'Foto angehängt',
  uploadPhoto: 'Foto hochladen', stopRecording: 'Aufnahme stoppen',
  speak: 'Sprechen', listening: 'Ich höre zu...', send: 'Senden',
  invalidFile: 'Ungültige Datei (max 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Dieses Foto analysieren',
  noSignup: 'Keine Registrierung · Erste Frage kostenlos',
  statsFree: 'Kostenlos starten · Keine Kreditkarte · 24/7 verfügbar',
  demoLabel: 'Oli in Aktion',
  demoSubtitle: 'Krankheiten, Schnitt, Bewässerung, Anbauplanung und vieles mehr',
  tabDiagnosis: '🔬 Diagnose', tabPlanning: '📐 Planung',
  confidence: 'Vertrauen', organic: '🌿 Bio', chemical: '🧪 Chemisch',
  agronomicData: 'Basierend auf agronomischen Daten',
  howLabel: 'So funktioniert es', howTitle: 'Drei einfache Schritte',
  rolesLabel: 'Für jede Rolle in der Landwirtschaft',
  rolesTitle: 'Oli passt jede Antwort an den Fragesteller an',
  rolesInstruction: 'Wähle eine Rolle, um echte Fragen und Antworten zu sehen',
  tryAs: (r) => `Als ${r} ausprobieren →`,
  featuresHeading: 'Funktionen', testimonialsLabel: 'Was Landwirte sagen',
  pricingLabel: 'Preise', pricingTitle: 'Kostenlos starten',
  pricingSubtitle: 'Upgrade wenn du mehr benötigst',
  billingMonthly: 'Monatlich', billingAnnual: 'Jährlich',
  perMonth: '/ Monat', perYear: '/ Jahr', noCreditCard: 'Keine Kreditkarte', freeName: 'Starter',
  freeTagline: 'Für Hobbygärtner und neugierige Anbauer',
  freeFeatures: ['20 Fragen / Monat', 'Krankheitsdiagnose per Foto', 'Behandlungsplan mit Dosierungen', '7-Tage-Eingriffshistorie', '1 Feldbericht pro Monat', 'Bis zu 3 Felder', 'Chat-Erinnerungen'],
  getStartedFree: 'Kostenlos starten',
  proYearlyNote: 'oder €49 / Jahr — 18% sparen',
  proTwoYearNote: 'oder €79 für 2 Jahre — bestes Preis-Leistungs-Verhältnis',
  proTagline: 'Für Landwirte und Anbauer, die von ihren Kulturen abhängen',
  proFeatures: ['Unbegrenzte Fragen', 'Unbegrenzte Felder + Kulturgedächtnis', 'Vollständige Eingriffshistorie', 'Bewässerungs- und Pflanzberechnungen', 'Unbegrenzte Feld-PDF-Berichte', 'Chat-Erinnerungen', 'Intelligente Wetterwarnungen'],
  tryPro: 'Pro testen',
  agronomistName: 'Master', agronomistBadge: 'Für Profis',
  agronomistYearlyNote: 'oder €490 / Jahr — 17% sparen',
  agronomistTwoYearNote: 'oder €790 für 2 Jahre — bestes Preis-Leistungs-Verhältnis',
  agronomistTagline: 'Für Agronomen, die mehrere Kunden beraten',
  agronomistFeatures: ['Alles in Pro enthalten', 'Unbegrenzte Kundenverwaltung', 'Felder und Eingriffshistorie pro Kunde', 'Wissenschaftliche Berechnungen (ETc, NPK)', 'Markenberichte im PDF-Format für Kunden', 'Chat-Erinnerungen'],
  startAgronomist: 'Mit Master starten',
  enterpriseBadge: 'Individuell', enterpriseContact: 'Kontakt aufnehmen',
  enterpriseSubtitle: 'Für Genossenschaften und Agrarbetriebe, die Agronomteams verwalten',
  enterpriseFeatures: ['Alles in Master enthalten', 'Mehrere Plätze / Teamkonten', 'White-Label- oder Co-Branding-Berichte', 'Prioritäts-Support', 'Individuelle Integrationen auf Anfrage', 'Chat-Erinnerungen'],
  getInTouch: 'Kontakt aufnehmen',
  ctaHeadline: 'Hör auf zu raten.', ctaBody: 'Oli ist kostenlos zum Starten. Keine Registrierung, keine Kreditkarte.',
  trialBadge: '30 Tage Pro kostenlos testen',
  ctaButton: 'Oli jetzt testen', ctaFine: 'Kostenlos · Keine Karte · 24/7 verfügbar',
  privacy: 'Datenschutz', terms: 'Nutzungsbedingungen',
  docTitle: 'Oli — Dein KI-Agrarberater | Landwirtschaftliche Beratung 24/7',
  metaDesc: 'Oli ist dein persönlicher Agrarberater. Krankheitsdiagnose, Feldplanung, Bewässerungsmanagement. Immer verfügbar, immer lernend.',
  ogTitle: 'Oli — Dein KI-Agrarberater, 24/7', ogLocale: 'de_DE', speechLang: 'de-DE',
  askOli: 'Frag Oli...',
};

export const LANDING_DICT: Record<Lang, LandingT> = { el, en, it, es, fr, ar, tr, ro, bg, sq, pt, de };
