import type { Lang } from './i18n';

export interface LandingT {
  tryFree: string; openApp: string;
  heroBadge: string; heroH1: [string, string]; heroSubtitle: string;
  heroPlaceholder: string; heroPlaceholderHint: string;
  removePhoto: string; photoAttached: string; uploadPhoto: string;
  stopRecording: string; speak: string; listening: string; send: string;
  invalidFile: string; analyzePhoto: string; noSignup: string;
  statsFree: string;
  demoLabel: string; demoSubtitle: string;
  tabDiagnosis: string; tabPlanning: string;
  confidence: string; organic: string; chemical: string; agronomicData: string;
  howLabel: string; howTitle: string;
  rolesLabel: string; rolesTitle: string; rolesInstruction: string;
  tryAs: (role: string) => string;
  featuresHeading: string; testimonialsLabel: string;
  pricingLabel: string; pricingTitle: string; pricingSubtitle: string;
  billingMonthly: string; billingAnnual: string;
  perMonth: string; perYear: string; noCreditCard: string; freeName: string;
  freeFeatures: string[]; getStartedFree: string;
  proYearlyNote: string; proTwoYearNote: string; proFeatures: string[]; tryPro: string;
  agronomistName: string; agronomistBadge: string;
  agronomistYearlyNote: string; agronomistTwoYearNote: string; agronomistTagline: string;
  agronomistFeatures: string[]; startAgronomist: string;
  enterpriseBadge: string; enterpriseContact: string;
  enterpriseSubtitle: string; enterpriseFeatures: string[]; getInTouch: string;
  ctaHeadline: string; ctaBody: string; ctaButton: string; ctaFine: string;
  privacy: string; terms: string;
  docTitle: string; metaDesc: string; ogTitle: string; ogLocale: string;
  speechLang: string; askOli: string;
}

const el: LandingT = {
  tryFree: 'Δοκίμασε δωρεάν', openApp: 'Άνοιξε',
  heroBadge: 'Ο AI Γεωπόνος σου · 24/7',
  heroH1: ['Ο γεωπόνος σου.', 'Πάντα μαζί σου.'],
  heroSubtitle: 'Διάγνωση ασθενειών, σχεδιασμός φύτευσης, άρδευση, αναστήλωση χωραφιών. Από σπορά μέχρι συγκομιδή, ο Oli μαθαίνει τις καλλιέργειές σου.',
  heroPlaceholder: 'Ρώτα ή ανέβασε φωτογραφία...',
  heroPlaceholderHint: '(Shift+Enter για νέα γραμμή)',
  removePhoto: 'Αφαίρεση φωτογραφίας', photoAttached: 'Φωτογραφία επισυνάφθηκε',
  uploadPhoto: 'Ανέβασε φωτογραφία', stopRecording: 'Σταμάτα εγγραφή',
  speak: 'Ομιλία', listening: 'Ακούω...', send: 'Αποστολή',
  invalidFile: 'Μη έγκυρο αρχείο (μέγιστο 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Ανάλυσε αυτή τη φωτογραφία',
  noSignup: 'Χωρίς εγγραφή · Η πρώτη ερώτηση είναι δωρεάν',
  statsFree: 'Δωρεάν για να ξεκινήσεις · Χωρίς πιστωτική κάρτα · Διαθέσιμος 24/7',
  demoLabel: 'Ο Oli σε δράση',
  demoSubtitle: 'Ασθένειες, κλάδεμα, λίπανση, σχεδιασμός φύτευσης και πολλά άλλα',
  tabDiagnosis: '🔬 Διάγνωση', tabPlanning: '📐 Σχεδιασμός',
  confidence: 'βεβαιότητα', organic: '🌿 Βιολογικό', chemical: '🧪 Χημικό',
  agronomicData: 'Βασισμένο σε αγρονομικά δεδομένα',
  howLabel: 'Πώς λειτουργεί', howTitle: 'Τρία απλά βήματα',
  rolesLabel: 'Για κάθε ρόλο στη γεωργία',
  rolesTitle: 'Ο Oli απαντάει διαφορετικά σε κάθε χρήστη',
  rolesInstruction: 'Κάνε κλικ σε ρόλο για να δεις πραγματικές ερωτήσεις και απαντήσεις',
  tryAs: (r) => `Δοκίμασε ως ${r} →`,
  featuresHeading: 'Χαρακτηριστικά', testimonialsLabel: 'Τι λένε οι αγρότες',
  pricingLabel: 'Τιμολόγηση', pricingTitle: 'Ξεκίνα δωρεάν',
  pricingSubtitle: 'Αναβάθμισε όταν χρειαστείς περισσότερα',
  billingMonthly: 'Μηνιαία', billingAnnual: 'Ετήσια',
  perMonth: '/ μήνα', perYear: '/ χρόνο', noCreditCard: 'Χωρίς πιστωτική κάρτα', freeName: 'Starter',
  freeFeatures: ['20 ερωτήσεις / μήνα', 'Διάγνωση ασθενειών από φωτογραφία', 'Πλάνο θεραπείας με δόσεις', 'Ιστορικό συνομιλιών'],
  getStartedFree: 'Ξεκίνα δωρεάν',
  proYearlyNote: 'ή €49 / χρόνο — εξοικονομείς 18%',
  proTwoYearNote: 'ή €79 για 2 χρόνια — καλύτερη αξία',
  proFeatures: ['Απεριόριστες ερωτήσεις & χωράφια', 'Μνήμη καλλιεργειών — θυμάται κάθε παρέμβαση', 'Αναγνώριση ελλείψεων θρεπτικών στοιχείων', 'Ανάγνωση εδαφολογικών & φυλλοδιαγνωστικών αναλύσεων', 'Παρακολούθηση θεραπειών & αρχείο παρεμβάσεων', 'Υπολογισμοί άρδευσης, φύτευσης & NPK', 'Μηνιαίες αναφορές χωραφιών σε PDF'],
  tryPro: 'Δοκίμασε Pro',
  agronomistName: 'Master', agronomistBadge: 'Για επαγγελματίες',
  agronomistYearlyNote: 'ή €490 / χρόνο — εξοικονομείς 17%',
  agronomistTwoYearNote: 'ή €790 για 2 χρόνια — καλύτερη αξία',
  agronomistTagline: 'Ο επαγγελματικός AI βοηθός για γεωπόνους και γεωτεχνικούς.',
  agronomistFeatures: ['Απεριόριστες ερωτήσεις', 'Απεριόριστα χωράφια & παραγωγοί', 'Πρόσβαση από κάθε συσκευή', 'Ανάγνωση εδαφολογικών & φυλλοδιαγνωστικών αναλύσεων', 'Ιστορικό παρεμβάσεων ανά πελάτη', 'Επιστημονικοί υπολογισμοί (ETc, NPK)', 'Απεριόριστες επώνυμες PDF αναφορές & αξιολογήσεις'],
  startAgronomist: 'Ξεκίνα ως Master',
  enterpriseBadge: 'Προσαρμοσμένο', enterpriseContact: 'Κατόπιν επικοινωνίας',
  enterpriseSubtitle: 'Για συλλόγους, συνεταιρισμούς & εταιρείες αγροεφοδίων',
  enterpriseFeatures: ['Απεριόριστα χωράφια & παραγωγοί', 'Απεριόριστες αναφορές & αναλύσεις', 'Εξαγωγή δεδομένων CSV / Excel', 'Πολλαπλοί χρήστες, πολλαπλές συσκευές', 'Ιδιωτικές ή συνδεδεμένες αναφορές', 'Πρόσβαση API κατόπιν αιτήματος', 'Προτεραιότητα υποστήριξης & προσαρμοσμένες ενσωματώσεις'],
  getInTouch: 'Επικοινωνήστε μαζί μας',
  ctaHeadline: 'Σταμάτα να μαντεύεις.', ctaBody: 'Ο Oli είναι δωρεάν για να ξεκινήσεις. Χωρίς εγγραφή, χωρίς πιστωτική κάρτα.',
  ctaButton: 'Δοκίμασε τον Oli τώρα', ctaFine: 'Δωρεάν · Χωρίς πιστωτική κάρτα · Πάντα διαθέσιμος',
  privacy: 'Απόρρητο', terms: 'Όροι',
  docTitle: 'Oli — Ο AI Γεωπόνος σου | 24/7 Συμβουλές Καλλιεργειών',
  metaDesc: 'Ο Oli είναι ο προσωπικός σου γεωπόνος. Διάγνωση ασθενειών, σχέδια θεραπείας, σχεδιασμός φύτευσης, άρδευση, αναστήλωση χωραφιών.',
  ogTitle: 'Oli — Ο AI Γεωπόνος σου 24/7', ogLocale: 'el_GR', speechLang: 'el-GR',
  askOli: 'Ρώτα τον Oli...',
};

const en: LandingT = {
  tryFree: 'Try free', openApp: 'Open app',
  heroBadge: 'Your AI Agronomist · 24/7',
  heroH1: ['Your personal agronomist.', 'With you 24/7.'],
  heroSubtitle: 'Diagnose diseases, plan your fields, set up irrigation, rehabilitate old groves. From planting to harvest, Oli learns your crops.',
  heroPlaceholder: 'Ask or upload a photo...',
  heroPlaceholderHint: '(Shift+Enter for new line)',
  removePhoto: 'Remove photo', photoAttached: 'Photo attached',
  uploadPhoto: 'Upload photo', stopRecording: 'Stop recording',
  speak: 'Speak', listening: 'Listening...', send: 'Send',
  invalidFile: 'Invalid file (max 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analyze this photo',
  noSignup: 'No sign-up required · First question is free',
  statsFree: 'Free to start · No credit card · Available 24/7',
  demoLabel: 'Oli in action',
  demoSubtitle: 'Diseases, pruning, irrigation, planting plans and much more',
  tabDiagnosis: '🔬 Diagnosis', tabPlanning: '📐 Planning',
  confidence: 'confidence', organic: '🌿 Organic', chemical: '🧪 Chemical',
  agronomicData: 'Based on agronomic data',
  howLabel: 'How it works', howTitle: 'Three simple steps',
  rolesLabel: 'For every role in agriculture',
  rolesTitle: 'Oli tailors every answer to who is asking',
  rolesInstruction: 'Select a role to see real questions and answers',
  tryAs: (r) => `Try as ${r} →`,
  featuresHeading: 'Features', testimonialsLabel: 'What farmers say',
  pricingLabel: 'Pricing', pricingTitle: 'Start for free',
  pricingSubtitle: 'Upgrade when you need more',
  billingMonthly: 'Monthly', billingAnnual: 'Annual',
  perMonth: '/ month', perYear: '/ year', noCreditCard: 'No credit card required', freeName: 'Starter',
  freeFeatures: ['20 questions / month', 'Crop disease diagnosis from photo', 'Treatment plan with dosages', 'Conversation history'],
  getStartedFree: 'Get started free',
  proYearlyNote: 'or €49 / year — save 18%',
  proTwoYearNote: 'or €79 for 2 years — best value',
  proFeatures: ['Unlimited questions & fields', 'Crop memory — remembers every intervention', 'Nutrient deficiency recognition', 'Reads soil & leaf lab analysis', 'Treatment follow-up & intervention log', 'Irrigation, planting & NPK calculations', 'Monthly field reports as PDF'],
  tryPro: 'Try Pro',
  agronomistName: 'Master', agronomistBadge: 'For professionals',
  agronomistYearlyNote: 'or €490 / year — save 17%',
  agronomistTwoYearNote: 'or €790 for 2 years — best value',
  agronomistTagline: 'Your AI research partner. Built for agricultural professionals.',
  agronomistFeatures: ['Unlimited questions', 'Unlimited fields & growers', 'Multi-device access', 'Reads soil & leaf lab analysis', 'Intervention history per client', 'Scientific calculations (ETc, NPK)', 'Unlimited branded PDF reports & assessments'],
  startAgronomist: 'Start with Master',
  enterpriseBadge: 'Custom', enterpriseContact: 'Contact us',
  enterpriseSubtitle: 'For cooperatives, associations & agri-input companies',
  enterpriseFeatures: ['Unlimited fields & growers', 'Unlimited reports & analytics', 'Data export CSV / Excel', 'Multiple users, multi-device', 'White-label or co-branded reports', 'API access on request', 'Priority support & custom integrations'],
  getInTouch: 'Get in touch',
  ctaHeadline: 'Stop guessing.', ctaBody: 'Oli is free to start. No sign-up required, no credit card.',
  ctaButton: 'Try Oli now', ctaFine: 'Free to start · No credit card · Available 24/7',
  privacy: 'Privacy', terms: 'Terms',
  docTitle: 'Oli — Your AI Agronomist | Farming Advice 24/7',
  metaDesc: 'Oli is your personal agronomist. Diagnose crop diseases, plan your fields, set up irrigation, rehabilitate old groves. Always available, always learning.',
  ogTitle: 'Oli — Your AI Agronomist, 24/7', ogLocale: 'en_US', speechLang: 'en-US',
  askOli: 'Ask Oli...',
};

const it: LandingT = {
  tryFree: 'Prova gratis', openApp: 'Apri app',
  heroBadge: 'Il tuo Agronomo AI · 24/7',
  heroH1: ['Il tuo agronomo personale.', 'Sempre con te.'],
  heroSubtitle: "Diagnostica malattie, pianifica i campi, gestisci l'irrigazione, recupera terreni abbandonati. Dalla semina al raccolto, Oli impara le tue colture.",
  heroPlaceholder: 'Fai una domanda o carica una foto...',
  heroPlaceholderHint: '(Shift+Invio per nuova riga)',
  removePhoto: 'Rimuovi foto', photoAttached: 'Foto allegata',
  uploadPhoto: 'Carica foto', stopRecording: 'Interrompi registrazione',
  speak: 'Parla', listening: 'In ascolto...', send: 'Invia',
  invalidFile: 'File non valido (max 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analizza questa foto',
  noSignup: 'Nessuna registrazione · Prima domanda gratuita',
  statsFree: 'Gratis per iniziare · Nessuna carta di credito · Disponibile 24/7',
  demoLabel: 'Oli in azione',
  demoSubtitle: 'Malattie, potatura, irrigazione, pianificazione colture e molto altro',
  tabDiagnosis: '🔬 Diagnosi', tabPlanning: '📐 Pianificazione',
  confidence: 'affidabilità', organic: '🌿 Biologico', chemical: '🧪 Chimico',
  agronomicData: 'Basato su dati agronomici',
  howLabel: 'Come funziona', howTitle: 'Tre semplici passi',
  rolesLabel: 'Per ogni ruolo in agricoltura',
  rolesTitle: 'Oli adatta ogni risposta a chi fa la domanda',
  rolesInstruction: 'Seleziona un ruolo per vedere domande e risposte reali',
  tryAs: (r) => `Prova come ${r} →`,
  featuresHeading: 'Funzionalità', testimonialsLabel: 'Cosa dicono gli agricoltori',
  pricingLabel: 'Prezzi', pricingTitle: 'Inizia gratis',
  pricingSubtitle: 'Aggiorna quando hai bisogno di più',
  billingMonthly: 'Mensile', billingAnnual: 'Annuale',
  perMonth: '/ mese', perYear: '/ anno', noCreditCard: 'Nessuna carta di credito', freeName: 'Starter',
  freeFeatures: ['20 domande / mese', 'Diagnosi malattie da foto', 'Piano di trattamento con dosaggi', 'Cronologia conversazioni'],
  getStartedFree: 'Inizia gratis',
  proYearlyNote: 'o €49 / anno — risparmia 18%',
  proTwoYearNote: 'o €79 per 2 anni — miglior valore',
  proFeatures: ['Domande e campi illimitati', 'Memoria colture — ricorda ogni intervento', 'Riconoscimento carenze nutrizionali', 'Legge analisi del suolo e fogliari', 'Monitoraggio trattamenti e registro interventi', 'Calcoli irrigazione, piantagione e NPK', 'Rapporti mensili dei campi in PDF'],
  tryPro: 'Prova Pro',
  agronomistName: 'Master', agronomistBadge: 'Per professionisti',
  agronomistYearlyNote: 'o €490 / anno — risparmia 17%',
  agronomistTwoYearNote: 'o €790 per 2 anni — miglior valore',
  agronomistTagline: 'Il tuo assistente AI professionale per agronomi e tecnici agricoli.',
  agronomistFeatures: ['Domande illimitate', 'Campi e produttori illimitati', 'Accesso multi-dispositivo', 'Legge analisi del suolo e fogliari', 'Storico interventi per cliente', 'Calcoli scientifici (ETc, NPK)', 'Rapporti PDF illimitati con il tuo marchio'],
  startAgronomist: 'Inizia con Master',
  enterpriseBadge: 'Personalizzato', enterpriseContact: 'Contattaci',
  enterpriseSubtitle: 'Per cooperative, consorzi e aziende agri-input',
  enterpriseFeatures: ['Campi e produttori illimitati', 'Rapporti e analisi illimitati', 'Esportazione dati CSV / Excel', 'Utenti multipli, multi-dispositivo', 'Rapporti white-label o co-branded', 'Accesso API su richiesta', 'Supporto prioritario e integrazioni personalizzate'],
  getInTouch: 'Contattaci',
  ctaHeadline: 'Smettila di indovinare.', ctaBody: 'Oli è gratis per iniziare. Nessuna registrazione, nessuna carta di credito.',
  ctaButton: 'Prova Oli adesso', ctaFine: 'Gratis · Nessuna carta · Disponibile 24/7',
  privacy: 'Privacy', terms: 'Termini',
  docTitle: 'Oli — Il tuo Agronomo AI | Consulenza Agricola 24/7',
  metaDesc: "Oli è il tuo agronomo personale. Diagnosi malattie, pianifica i campi, gestisci l'irrigazione. Sempre disponibile, impara sempre.",
  ogTitle: 'Oli — Il tuo Agronomo AI, 24/7', ogLocale: 'it_IT', speechLang: 'it-IT',
  askOli: 'Chiedi a Oli...',
};

const es: LandingT = {
  tryFree: 'Prueba gratis', openApp: 'Abrir app',
  heroBadge: 'Tu Agrónomo IA · 24/7',
  heroH1: ['Tu agrónomo personal.', 'Siempre a tu lado.'],
  heroSubtitle: 'Diagnóstico de enfermedades, planificación de cultivos, riego, rehabilitación de fincas. De la siembra a la cosecha, Oli aprende tus cultivos.',
  heroPlaceholder: 'Haz una pregunta o sube una foto...',
  heroPlaceholderHint: '(Shift+Intro para nueva línea)',
  removePhoto: 'Eliminar foto', photoAttached: 'Foto adjuntada',
  uploadPhoto: 'Subir foto', stopRecording: 'Detener grabación',
  speak: 'Hablar', listening: 'Escuchando...', send: 'Enviar',
  invalidFile: 'Archivo no válido (máx 10MB, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analizar esta foto',
  noSignup: 'Sin registro · Primera pregunta gratis',
  statsFree: 'Gratis para empezar · Sin tarjeta de crédito · Disponible 24/7',
  demoLabel: 'Oli en acción',
  demoSubtitle: 'Enfermedades, poda, riego, planificación de cultivos y mucho más',
  tabDiagnosis: '🔬 Diagnóstico', tabPlanning: '📐 Planificación',
  confidence: 'confianza', organic: '🌿 Ecológico', chemical: '🧪 Químico',
  agronomicData: 'Basado en datos agronómicos',
  howLabel: 'Cómo funciona', howTitle: 'Tres pasos simples',
  rolesLabel: 'Para cada rol en la agricultura',
  rolesTitle: 'Oli adapta cada respuesta a quien pregunta',
  rolesInstruction: 'Selecciona un rol para ver preguntas y respuestas reales',
  tryAs: (r) => `Probar como ${r} →`,
  featuresHeading: 'Características', testimonialsLabel: 'Lo que dicen los agricultores',
  pricingLabel: 'Precios', pricingTitle: 'Empieza gratis',
  pricingSubtitle: 'Mejora tu plan cuando necesites más',
  billingMonthly: 'Mensual', billingAnnual: 'Anual',
  perMonth: '/ mes', perYear: '/ año', noCreditCard: 'Sin tarjeta de crédito', freeName: 'Starter',
  freeFeatures: ['20 preguntas / mes', 'Diagnóstico de enfermedades por foto', 'Plan de tratamiento con dosis', 'Historial de conversaciones'],
  getStartedFree: 'Empezar gratis',
  proYearlyNote: 'o €49 / año — ahorra 18%',
  proTwoYearNote: 'o €79 por 2 años — mejor valor',
  proFeatures: ['Preguntas y campos ilimitados', 'Memoria de cultivos — recuerda cada intervención', 'Reconocimiento de deficiencias nutricionales', 'Lee análisis de suelo y foliares', 'Seguimiento de tratamientos y registro', 'Cálculos de riego, siembra y NPK', 'Informes mensuales de campos en PDF'],
  tryPro: 'Probar Pro',
  agronomistName: 'Master', agronomistBadge: 'Para profesionales',
  agronomistYearlyNote: 'o €490 / año — ahorra 17%',
  agronomistTwoYearNote: 'o €790 por 2 años — mejor valor',
  agronomistTagline: 'Tu asistente IA profesional para agrónomos y técnicos agrícolas.',
  agronomistFeatures: ['Preguntas ilimitadas', 'Campos y productores ilimitados', 'Acceso multi-dispositivo', 'Lee análisis de suelo y foliares', 'Historial de intervenciones por cliente', 'Cálculos científicos (ETc, NPK)', 'Informes PDF ilimitados con tu marca'],
  startAgronomist: 'Empezar con Master',
  enterpriseBadge: 'Personalizado', enterpriseContact: 'Contáctanos',
  enterpriseSubtitle: 'Para cooperativas, asociaciones y empresas agro-insumos',
  enterpriseFeatures: ['Campos y productores ilimitados', 'Informes y análisis ilimitados', 'Exportación de datos CSV / Excel', 'Múltiples usuarios, multi-dispositivo', 'Informes white-label o co-branded', 'Acceso API bajo petición', 'Soporte prioritario e integraciones personalizadas'],
  getInTouch: 'Contáctanos',
  ctaHeadline: 'Deja de adivinar.', ctaBody: 'Oli es gratis para empezar. Sin registro, sin tarjeta de crédito.',
  ctaButton: 'Prueba Oli ahora', ctaFine: 'Gratis · Sin tarjeta · Disponible 24/7',
  privacy: 'Privacidad', terms: 'Términos',
  docTitle: 'Oli — Tu Agrónomo IA | Asesoramiento Agrícola 24/7',
  metaDesc: 'Oli es tu agrónomo personal. Diagnóstico de enfermedades, planifica tus campos, gestiona el riego. Siempre disponible, siempre aprendiendo.',
  ogTitle: 'Oli — Tu Agrónomo IA, 24/7', ogLocale: 'es_ES', speechLang: 'es-ES',
  askOli: 'Pregunta a Oli...',
};

const fr: LandingT = {
  tryFree: 'Essai gratuit', openApp: "Ouvrir l'app",
  heroBadge: 'Ton Agronome IA · 24/7',
  heroH1: ['Ton agronome personnel.', 'Toujours avec toi.'],
  heroSubtitle: "Diagnostic des maladies, planification des cultures, irrigation, réhabilitation des champs. De la plantation à la récolte, Oli apprend tes cultures.",
  heroPlaceholder: 'Pose une question ou charge une photo...',
  heroPlaceholderHint: '(Maj+Entrée pour nouvelle ligne)',
  removePhoto: 'Supprimer la photo', photoAttached: 'Photo jointe',
  uploadPhoto: 'Charger une photo', stopRecording: "Arrêter l'enregistrement",
  speak: 'Parler', listening: "J'écoute...", send: 'Envoyer',
  invalidFile: 'Fichier invalide (max 10Mo, JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'Analyser cette photo',
  noSignup: 'Sans inscription · Première question gratuite',
  statsFree: 'Gratuit pour commencer · Sans carte bancaire · Disponible 24/7',
  demoLabel: 'Oli en action',
  demoSubtitle: 'Maladies, taille, irrigation, planification des cultures et bien plus',
  tabDiagnosis: '🔬 Diagnostic', tabPlanning: '📐 Planification',
  confidence: 'confiance', organic: '🌿 Biologique', chemical: '🧪 Chimique',
  agronomicData: 'Basé sur des données agronomiques',
  howLabel: 'Comment ça marche', howTitle: 'Trois étapes simples',
  rolesLabel: "Pour chaque rôle dans l'agriculture",
  rolesTitle: 'Oli adapte chaque réponse à qui pose la question',
  rolesInstruction: 'Sélectionne un rôle pour voir de vraies questions et réponses',
  tryAs: (r) => `Essayer en tant que ${r} →`,
  featuresHeading: 'Fonctionnalités', testimonialsLabel: 'Ce que disent les agriculteurs',
  pricingLabel: 'Tarifs', pricingTitle: 'Commence gratuitement',
  pricingSubtitle: "Passe à un plan supérieur si tu as besoin de plus",
  billingMonthly: 'Mensuel', billingAnnual: 'Annuel',
  perMonth: '/ mois', perYear: '/ an', noCreditCard: 'Sans carte bancaire', freeName: 'Starter',
  freeFeatures: ['20 questions / mois', 'Diagnostic maladie par photo', 'Plan de traitement avec dosages', 'Historique des conversations'],
  getStartedFree: 'Commencer gratuitement',
  proYearlyNote: 'ou 49€ / an — économise 18%',
  proTwoYearNote: 'ou 79€ pour 2 ans — meilleur rapport',
  proFeatures: ['Questions et champs illimités', 'Mémoire cultures — se souvient de chaque intervention', 'Reconnaissance des carences nutritionnelles', 'Lit les analyses de sol et foliaires', 'Suivi des traitements et journal des interventions', 'Calculs irrigation, plantation et NPK', 'Rapports mensuels des champs en PDF'],
  tryPro: 'Essayer Pro',
  agronomistName: 'Master', agronomistBadge: 'Pour les professionnels',
  agronomistYearlyNote: 'ou 490€ / an — économise 17%',
  agronomistTwoYearNote: 'ou 790€ pour 2 ans — meilleur rapport',
  agronomistTagline: "Ton assistant IA professionnel pour agronomes et techniciens agricoles.",
  agronomistFeatures: ['Questions illimitées', 'Champs et producteurs illimités', 'Accès multi-appareils', 'Lit les analyses de sol et foliaires', 'Historique des interventions par client', 'Calculs scientifiques (ETc, NPK)', 'Rapports PDF illimités avec ta marque'],
  startAgronomist: 'Commencer avec Master',
  enterpriseBadge: 'Sur mesure', enterpriseContact: 'Nous contacter',
  enterpriseSubtitle: "Pour coopératives, associations et fournisseurs agri-input",
  enterpriseFeatures: ['Champs et producteurs illimités', 'Rapports et analyses illimités', 'Export données CSV / Excel', 'Utilisateurs multiples, multi-appareils', 'Rapports white-label ou co-brandés', 'Accès API sur demande', 'Support prioritaire et intégrations personnalisées'],
  getInTouch: 'Nous contacter',
  ctaHeadline: 'Arrête de deviner.', ctaBody: 'Oli est gratuit pour commencer. Sans inscription, sans carte bancaire.',
  ctaButton: 'Essayer Oli maintenant', ctaFine: 'Gratuit · Sans carte · Disponible 24/7',
  privacy: 'Confidentialité', terms: 'Conditions',
  docTitle: 'Oli — Ton Agronome IA | Conseils Agricoles 24/7',
  metaDesc: "Oli est ton agronome personnel. Diagnostic des maladies, planifie tes champs, gère l'irrigation. Toujours disponible, toujours en apprentissage.",
  ogTitle: 'Oli — Ton Agronome IA, 24/7', ogLocale: 'fr_FR', speechLang: 'fr-FR',
  askOli: 'Demande à Oli...',
};

const ar: LandingT = {
  tryFree: 'جرّب مجانًا', openApp: 'افتح التطبيق',
  heroBadge: 'مستشارك الزراعي الذكي · 24/7',
  heroH1: ['مستشارك الزراعي الشخصي.', 'معك في كل وقت.'],
  heroSubtitle: 'تشخيص الأمراض، تخطيط الحقول، إدارة الري، تأهيل البساتين. من البذر حتى الحصاد، يتعلم أولي محاصيلك.',
  heroPlaceholder: 'اطرح سؤالًا أو ارفع صورة...',
  heroPlaceholderHint: '(Shift+Enter لسطر جديد)',
  removePhoto: 'حذف الصورة', photoAttached: 'تم إرفاق الصورة',
  uploadPhoto: 'رفع صورة', stopRecording: 'إيقاف التسجيل',
  speak: 'تحدث', listening: 'أستمع...', send: 'إرسال',
  invalidFile: 'ملف غير صالح (الحد الأقصى 10MB، JPEG/PNG/WEBP/HEIC)',
  analyzePhoto: 'تحليل هذه الصورة',
  noSignup: 'بدون تسجيل · السؤال الأول مجاني',
  statsFree: 'مجاني للبدء · بدون بطاقة ائتمان · متاح 24/7',
  demoLabel: 'أولي في العمل',
  demoSubtitle: 'الأمراض، التقليم، الري، تخطيط الزراعة وأكثر بكثير',
  tabDiagnosis: '🔬 تشخيص', tabPlanning: '📐 تخطيط',
  confidence: 'دقة', organic: '🌿 عضوي', chemical: '🧪 كيميائي',
  agronomicData: 'مبني على بيانات زراعية',
  howLabel: 'كيف يعمل', howTitle: 'ثلاث خطوات بسيطة',
  rolesLabel: 'لكل دور في الزراعة',
  rolesTitle: 'أولي يكيّف كل إجابة حسب من يسأل',
  rolesInstruction: 'اختر دورًا لترى أسئلة وإجابات حقيقية',
  tryAs: (r) => `جرّب كـ${r} →`,
  featuresHeading: 'المميزات', testimonialsLabel: 'ما يقوله المزارعون',
  pricingLabel: 'الأسعار', pricingTitle: 'ابدأ مجانًا',
  pricingSubtitle: 'طوّر خطتك عندما تحتاج أكثر',
  billingMonthly: 'شهري', billingAnnual: 'سنوي',
  perMonth: '/ شهر', perYear: '/ سنة', noCreditCard: 'بدون بطاقة ائتمان', freeName: 'Starter',
  freeFeatures: ['20 سؤال / شهر', 'تشخيص أمراض المحاصيل من صورة', 'خطة علاج بالجرعات', 'سجل المحادثات'],
  getStartedFree: 'ابدأ مجانًا',
  proYearlyNote: 'أو 49€ / سنة — وفّر 18%',
  proTwoYearNote: 'أو 79€ لسنتين — أفضل قيمة',
  proFeatures: ['أسئلة وحقول غير محدودة', 'ذاكرة المحاصيل — يتذكر كل تدخل', 'تشخيص نقص العناصر الغذائية', 'يقرأ تحاليل التربة والأوراق', 'متابعة العلاج وسجل التدخلات', 'حسابات الري والزراعة و NPK', 'تقارير شهرية للحقول بصيغة PDF'],
  tryPro: 'جرّب Pro',
  agronomistName: 'Master', agronomistBadge: 'للمحترفين',
  agronomistYearlyNote: 'أو 490€ / سنة — وفّر 17%',
  agronomistTwoYearNote: 'أو 790€ لسنتين — أفضل قيمة',
  agronomistTagline: 'مساعدك الذكي المهني للمهندسين الزراعيين والمستشارين.',
  agronomistFeatures: ['أسئلة غير محدودة', 'حقول ومنتجون غير محدودين', 'وصول متعدد الأجهزة', 'يقرأ تحاليل التربة والأوراق', 'سجل التدخلات لكل عميل', 'حسابات علمية (ETc, NPK)', 'تقارير PDF غير محدودة بعلامتك التجارية'],
  startAgronomist: 'ابدأ مع Master',
  enterpriseBadge: 'مخصص', enterpriseContact: 'تواصل معنا',
  enterpriseSubtitle: 'للتعاونيات والجمعيات وشركات المستلزمات الزراعية',
  enterpriseFeatures: ['حقول ومنتجون غير محدودين', 'تقارير وتحليلات غير محدودة', 'تصدير البيانات CSV / Excel', 'مستخدمون متعددون، متعدد الأجهزة', 'تقارير white-label أو co-branded', 'وصول API عند الطلب', 'دعم أولوية وتكاملات مخصصة'],
  getInTouch: 'تواصل معنا',
  ctaHeadline: 'توقف عن التخمين.', ctaBody: 'أولي مجاني للبدء. بدون تسجيل، بدون بطاقة ائتمان.',
  ctaButton: 'جرّب أولي الآن', ctaFine: 'مجاني · بدون بطاقة · متاح 24/7',
  privacy: 'الخصوصية', terms: 'الشروط',
  docTitle: 'Oli — مستشارك الزراعي الذكي | نصائح زراعية 24/7',
  metaDesc: 'أولي هو مستشارك الزراعي الشخصي. تشخيص أمراض المحاصيل، تخطيط حقولك، إدارة الري. متاح دائمًا، يتعلم دائمًا.',
  ogTitle: 'Oli — مستشارك الزراعي الذكي، 24/7', ogLocale: 'ar_SA', speechLang: 'ar-SA',
  askOli: 'اسأل أولي...',
};

export const LANDING_DICT: Record<Lang, LandingT> = { el, en, it, es, fr, ar };
