/**
 * Branded "save the whole plan as a file" export.
 *
 * The plan is already rendered (and rehype-sanitized) inside the chat bubble.
 * `openPlanFile` takes that pre-rendered, already-safe innerHTML and drops it
 * into an Oli-branded print shell (same header/footer/green as the field
 * report in generateReport.ts), then opens it in a new tab that auto-prints —
 * so the grower can read it, save it as PDF, or print it.
 *
 * Gating decision (matches the field-report behaviour already shipped):
 *   free   → 1 file / month, shared with the report_count_month budget
 *   paid   → unlimited
 */

/** Escape user-controlled strings before inserting into HTML context. */
function h(s: string | null | undefined): string {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Build the full branded HTML document for a cultivation plan.
 *
 * IMPORTANT: `bodyHtml` MUST already be sanitized HTML (it comes from the live
 * rehype-sanitize'd chat DOM). It is injected raw. Only the title/userName,
 * which are user-controlled plain text, are escaped here.
 */
export function buildPlanFileHtml(bodyHtml: string, userName: string, lang: string): string {
  const el = lang === 'el';
  const today = new Date().toLocaleDateString(el ? 'el-GR' : 'en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  });
  const docTitle = el ? 'Πρόγραμμα Καλλιέργειας' : 'Cultivation Plan';

  return `<!DOCTYPE html>
<html lang="${h(lang)}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Oli — ${h(docTitle)}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:13px;line-height:1.55;color:#1b1c19;background:#fff}
    .page{max-width:820px;margin:0 auto;padding:32px 40px}
    /* Header */
    .hdr{display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #2EA043;padding-bottom:16px;margin-bottom:24px}
    .hdr-l{display:flex;align-items:center;gap:10px}
    .logo{font-size:20px;font-weight:700;color:#2EA043;line-height:1}
    .sub{font-size:10px;color:#777;margin-top:2px}
    .hdr-r{text-align:right;font-size:11px;color:#555;line-height:1.6}
    /* Plan body (rendered markdown) */
    .plan h1{font-size:19px;color:#194121;margin:18px 0 10px}
    .plan h2{font-size:16px;color:#194121;margin:18px 0 8px}
    .plan h3{font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#2EA043;margin:16px 0 6px}
    .plan p{margin:0 0 10px}
    .plan ul,.plan ol{margin:0 0 12px 22px}
    .plan li{margin:3px 0}
    .plan strong{color:#194121}
    .plan code{background:#f4fbf4;padding:1px 5px;border-radius:4px;font-size:12px}
    .plan blockquote{border-left:3px solid #c8e6c9;padding-left:12px;color:#555;margin:0 0 12px}
    .plan table{width:100%;border-collapse:collapse;font-size:12px;margin:0 0 14px}
    .plan th{background:#f4fbf4;padding:6px 8px;text-align:left;border-bottom:1px solid #c8e6c9;font-size:11px;color:#2EA043}
    .plan td{padding:5px 8px;border-bottom:1px solid #f0f0f0;vertical-align:top}
    .plan hr{border:none;border-top:1px solid #eee;margin:16px 0}
    /* Footer */
    .footer{margin-top:32px;padding-top:12px;border-top:1px solid #eee;text-align:center;font-size:10px;color:#aaa}
    @media print{.page{padding:16px 20px}}
  </style>
</head>
<body>
<div class="page">
  <div class="hdr">
    <div class="hdr-l">
      <svg width="26" height="26" viewBox="0 0 24 24" fill="#2EA043"><path d="M17 8C8 10 5.9 16.17 3.82 21.34L5.71 22l1-2.3A4.49 4.49 0 0 0 8 20C19 20 22 3 22 3c-1 2-8 2-13 6 0 0 .93-.98 2-2z"/></svg>
      <div>
        <div class="logo">Oli</div>
        <div class="sub">${el ? 'Ο AI Γεωπόνος σου' : 'Your AI Agronomist'}</div>
      </div>
    </div>
    <div class="hdr-r">
      ${userName ? `<b>${h(userName)}</b><br>` : ''}
      ${h(docTitle)}<br>
      ${h(today)}
    </div>
  </div>
  <div class="plan">${bodyHtml}</div>
  <div class="footer">ask-oli.com &mdash; ${el ? 'Δημιουργήθηκε από το Oli' : 'Generated by Oli'}</div>
</div>
<script>window.addEventListener('load',()=>window.print())</script>
</body>
</html>`;
}

/**
 * Open the branded plan file in a new tab and trigger the print dialog.
 * `bodyHtml` must be the pre-sanitized innerHTML from the chat bubble.
 */
export function openPlanFile(bodyHtml: string, userName: string, lang: string): void {
  const html = buildPlanFileHtml(bodyHtml, userName, lang);
  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}

/**
 * Consume one unit of the free-tier monthly file budget.
 *
 * Plan files share the same report_count_month budget as field reports
 * (free = 1/month). Paid tiers are unlimited and never touch the counter.
 *
 * Returns 'paywall' when a free user is out of budget (caller should show the
 * paywall and NOT open the file), or 'ok' when the file may be generated.
 */
export async function consumeReportQuota(
  appUserId: string,
  isFree: boolean,
): Promise<'ok' | 'paywall'> {
  if (!isFree) return 'ok';

  // Lazy import so the pure HTML builder above stays import-safe in unit tests
  // (top-level supabase import instantiates the client at module load).
  const { supabase } = await import('./supabase');

  const { data } = await supabase
    .from('users')
    .select('report_count_month')
    .eq('id', appUserId)
    .single();

  const count = data?.report_count_month ?? 0;
  if (count >= 1) return 'paywall';

  await supabase
    .from('users')
    .update({ report_count_month: count + 1 })
    .eq('id', appUserId);

  return 'ok';
}
