import { useState } from 'react';
import { FileText, Download, Share2, Loader2 } from 'lucide-react';
import ShareModal from './ShareModal';

interface FieldData {
  id: string;
  name: string;
  crop_type: string | null;
  size_ha: number | null;
  soil_type: string | null;
  irrigation_type: string | null;
  last_diagnosis: string | null;
  intervention_count?: number | null;
  pending_follow_up_count?: number | null;
}

interface TimelineItem {
  activity_type: string;
  title: string | null;
  activity_at: string;
  diagnosis?: string | null;
  product_applied?: string | null;
  outcome?: string | null;
}

interface Props {
  field: FieldData;
  timeline: TimelineItem[];
  growthStage: string | null;
  lang: string;
}

function generateReportHTML(field: FieldData, timeline: TimelineItem[], growthStage: string | null, lang: string): string {
  const l = lang === 'el' ? 'el' : 'en';
  const labels = {
    title: { en: 'Field Report', el: 'Αναφορά Χωραφιού' },
    fieldInfo: { en: 'Field Information', el: 'Στοιχεία Χωραφιού' },
    crop: { en: 'Crop', el: 'Καλλιέργεια' },
    size: { en: 'Size', el: 'Μέγεθος' },
    soil: { en: 'Soil', el: 'Έδαφος' },
    irrigation: { en: 'Irrigation', el: 'Άρδευση' },
    stage: { en: 'Growth Stage', el: 'Στάδιο Ανάπτυξης' },
    lastIssue: { en: 'Last Issue', el: 'Τελευταίο Πρόβλημα' },
    timeline: { en: 'Activity Timeline', el: 'Χρονολόγιο Δραστηριοτήτων' },
    interventions: { en: 'Interventions', el: 'Επεμβάσεις' },
    pending: { en: 'Pending Follow-ups', el: 'Εκκρεμείς Παρακολουθήσεις' },
    generated: { en: 'Generated by Oli', el: 'Δημιουργήθηκε από τον Oli' },
    na: { en: 'N/A', el: 'Δ/Υ' },
  };

  const date = new Date().toLocaleDateString(lang === 'el' ? 'el-GR' : 'en-GB', { year: 'numeric', month: 'long', day: 'numeric' });
  const na = labels.na[l];

  const timelineRows = timeline.slice(0, 20).map((item) => {
    const d = new Date(item.activity_at).toLocaleDateString(lang === 'el' ? 'el-GR' : 'en-GB');
    const type = item.activity_type === 'intervention' ? '💊' : '💬';
    return `<tr><td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:13px">${d}</td><td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:13px">${type} ${item.title || '-'}</td><td style="padding:6px 8px;border-bottom:1px solid #eee;font-size:13px">${item.outcome || '-'}</td></tr>`;
  }).join('');

  return `<!DOCTYPE html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${labels.title[l]} — ${field.name}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1b1c19;background:#fff;padding:32px;max-width:800px;margin:0 auto}h1{color:#194121;font-size:24px;margin-bottom:4px}h2{color:#194121;font-size:16px;margin:24px 0 12px;padding-bottom:6px;border-bottom:2px solid #e8f5e9}.subtitle{color:#606659;font-size:13px;margin-bottom:24px}.info-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 24px;margin-bottom:8px}.info-item{font-size:13px}.info-label{color:#606659;font-size:11px;text-transform:uppercase;letter-spacing:0.5px}table{width:100%;border-collapse:collapse}th{text-align:left;padding:8px;background:#f5f5f0;font-size:12px;text-transform:uppercase;letter-spacing:0.5px;color:#606659}.footer{margin-top:32px;padding-top:16px;border-top:1px solid #eee;text-align:center;font-size:11px;color:#999}@media print{body{padding:16px}}</style></head><body>
<h1>${labels.title[l]}: ${field.name}</h1>
<p class="subtitle">${date}</p>

<h2>${labels.fieldInfo[l]}</h2>
<div class="info-grid">
<div class="info-item"><span class="info-label">${labels.crop[l]}</span><br>${field.crop_type || na}</div>
<div class="info-item"><span class="info-label">${labels.size[l]}</span><br>${field.size_ha ? `${field.size_ha} ha` : na}</div>
<div class="info-item"><span class="info-label">${labels.soil[l]}</span><br>${field.soil_type || na}</div>
<div class="info-item"><span class="info-label">${labels.irrigation[l]}</span><br>${field.irrigation_type || na}</div>
${growthStage ? `<div class="info-item"><span class="info-label">${labels.stage[l]}</span><br>${growthStage}</div>` : ''}
<div class="info-item"><span class="info-label">${labels.lastIssue[l]}</span><br>${field.last_diagnosis || na}</div>
<div class="info-item"><span class="info-label">${labels.interventions[l]}</span><br>${field.intervention_count ?? 0}</div>
<div class="info-item"><span class="info-label">${labels.pending[l]}</span><br>${field.pending_follow_up_count ?? 0}</div>
</div>

${timeline.length > 0 ? `
<h2>${labels.timeline[l]}</h2>
<table><thead><tr><th>Date</th><th>Activity</th><th>Outcome</th></tr></thead><tbody>${timelineRows}</tbody></table>
` : ''}

<div class="footer">${labels.generated[l]} · askoli.ai · ${date}</div>
</body></html>`;
}

export default function ReportGenerator({ field, timeline, growthStage, lang }: Props) {
  const [generating, setGenerating] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const l = lang === 'el' ? 'el' : 'en';

  const handleGenerate = () => {
    setGenerating(true);
    try {
      const html = generateReportHTML(field, timeline, growthStage, lang);
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);

      // Open in new tab for print/save as PDF
      const win = window.open(url, '_blank');
      if (win) {
        win.addEventListener('load', () => {
          setTimeout(() => win.print(), 500);
        });
      }
    } finally {
      setGenerating(false);
    }
  };

  const handleShare = () => {
    const reportUrl = `${window.location.origin}/fields/${field.id}`;
    setShareUrl(reportUrl);
  };

  const labels = {
    generate: { en: 'Generate Report', el: 'Δημιουργία Αναφοράς' },
    share: { en: 'Share', el: 'Κοινοποίηση' },
  };

  return (
    <>
      <div className="mx-4 mt-3 flex gap-2">
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-medium text-white hover:bg-primary/90 disabled:opacity-50 transition-colors"
        >
          {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}
          {labels.generate[l]}
        </button>
        <button
          onClick={handleShare}
          className="flex items-center justify-center gap-2 rounded-xl border border-border bg-surface px-4 py-2.5 text-sm font-medium text-foreground hover:bg-background transition-colors"
        >
          <Share2 className="h-4 w-4" />
          {labels.share[l]}
        </button>
      </div>

      {shareUrl && (
        <ShareModal
          isOpen={!!shareUrl}
          onClose={() => setShareUrl(null)}
          url={shareUrl}
          title={`${field.name} — Oli Report`}
          lang={lang}
        />
      )}
    </>
  );
}
