-- ============================================================
-- Feature: Chat-triggered reminders + proactive field alerts
-- ============================================================

-- 1. scheduled_treatments — reminders created from chat or manually
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.scheduled_treatments (
  id              UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id         UUID         REFERENCES public.users(id)         ON DELETE CASCADE NOT NULL,
  field_id        UUID         REFERENCES public.fields(id)        ON DELETE CASCADE,
  crop_type       TEXT,
  task            TEXT         NOT NULL,
  notes           TEXT,
  due_at          TIMESTAMPTZ  NOT NULL,
  status          TEXT         DEFAULT 'pending'
                               CHECK (status IN ('pending', 'done', 'skipped')),
  source          TEXT         DEFAULT 'chat'
                               CHECK (source IN ('chat', 'manual')),
  push_sent_at    TIMESTAMPTZ,                    -- tracks when push was sent (avoid re-notify)
  conversation_id UUID         REFERENCES public.conversations(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ  DEFAULT NOW()
);

ALTER TABLE public.scheduled_treatments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own scheduled treatments"
  ON public.scheduled_treatments
  FOR ALL
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_scheduled_treatments_due
  ON public.scheduled_treatments (due_at)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_scheduled_treatments_user_field
  ON public.scheduled_treatments (user_id, field_id);

-- 2. field_alerts — proactive weather/seasonal alerts generated by AI
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.field_alerts (
  id          UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID         REFERENCES public.users(id)  ON DELETE CASCADE NOT NULL,
  field_id    UUID         REFERENCES public.fields(id) ON DELETE CASCADE,
  message     TEXT         NOT NULL,
  severity    TEXT         DEFAULT 'medium'
                           CHECK (severity IN ('low', 'medium', 'high')),
  source      TEXT         DEFAULT 'proactive'
                           CHECK (source IN ('proactive', 'system')),
  read_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ  DEFAULT NOW()
);

ALTER TABLE public.field_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users own field alerts"
  ON public.field_alerts
  FOR ALL
  USING  (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_field_alerts_user_unread
  ON public.field_alerts (user_id, created_at DESC)
  WHERE read_at IS NULL;

-- 3. Track last proactive alert per field to enforce cool-down
-- -------------------------------------------------------------------
ALTER TABLE public.fields
  ADD COLUMN IF NOT EXISTS last_proactive_alert_at TIMESTAMPTZ;
